/*Generated by WaveMaker Studio*/
package com.testingallprocedurescenarios.sample2;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

public class EmpPhotoId implements Serializable {

    private String photoFormat;
    private String empno;

    public String getPhotoFormat() {
        return this.photoFormat;
    }

    public void setPhotoFormat(String photoFormat) {
        this.photoFormat = photoFormat;
    }

    public String getEmpno() {
        return this.empno;
    }

    public void setEmpno(String empno) {
        this.empno = empno;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof EmpPhoto)) return false;
        final EmpPhoto empPhoto = (EmpPhoto) o;
        return Objects.equals(getPhotoFormat(), empPhoto.getPhotoFormat()) &&
                Objects.equals(getEmpno(), empPhoto.getEmpno());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPhotoFormat(),
                getEmpno());
    }
}