/*Generated by WaveMaker Studio*/
package com.testingallprocedurescenarios.sample2;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.util.Objects;

public class Vempdpt1Id implements Serializable {

    private String deptno;
    private String deptname;
    private String empno;
    private Character frstinit;
    private Character midinit;
    private String lastname;
    private String workdept;

    public String getDeptno() {
        return this.deptno;
    }

    public void setDeptno(String deptno) {
        this.deptno = deptno;
    }

    public String getDeptname() {
        return this.deptname;
    }

    public void setDeptname(String deptname) {
        this.deptname = deptname;
    }

    public String getEmpno() {
        return this.empno;
    }

    public void setEmpno(String empno) {
        this.empno = empno;
    }

    public Character getFrstinit() {
        return this.frstinit;
    }

    public void setFrstinit(Character frstinit) {
        this.frstinit = frstinit;
    }

    public Character getMidinit() {
        return this.midinit;
    }

    public void setMidinit(Character midinit) {
        this.midinit = midinit;
    }

    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getWorkdept() {
        return this.workdept;
    }

    public void setWorkdept(String workdept) {
        this.workdept = workdept;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Vempdpt1)) return false;
        final Vempdpt1 vempdpt1 = (Vempdpt1) o;
        return Objects.equals(getDeptno(), vempdpt1.getDeptno()) &&
                Objects.equals(getDeptname(), vempdpt1.getDeptname()) &&
                Objects.equals(getEmpno(), vempdpt1.getEmpno()) &&
                Objects.equals(getFrstinit(), vempdpt1.getFrstinit()) &&
                Objects.equals(getMidinit(), vempdpt1.getMidinit()) &&
                Objects.equals(getLastname(), vempdpt1.getLastname()) &&
                Objects.equals(getWorkdept(), vempdpt1.getWorkdept());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getDeptno(),
                getDeptname(),
                getEmpno(),
                getFrstinit(),
                getMidinit(),
                getLastname(),
                getWorkdept());
    }
}