/*Generated by WaveMaker Studio*/
package com.testingallprocedurescenarios.school_db.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class Scenario2Response implements Serializable {


    @ColumnAlias("content")
    private List<Scenario2ResponseContent> content;

    @ColumnAlias("academicyear")
    private String academicyear;

    public List<Scenario2ResponseContent> getContent() {
        return this.content;
    }

    public void setContent(List<Scenario2ResponseContent> content) {
        this.content = content;
    }

    public String getAcademicyear() {
        return this.academicyear;
    }

    public void setAcademicyear(String academicyear) {
        this.academicyear = academicyear;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Scenario2Response)) return false;
        final Scenario2Response scenario2response = (Scenario2Response) o;
        return Objects.equals(getContent(), scenario2response.getContent()) &&
                Objects.equals(getAcademicyear(), scenario2response.getAcademicyear());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getContent(),
                getAcademicyear());
    }
}