/*Generated by WaveMaker Studio*/
package com.testingallprocedurescenarios.wmstudio.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.servlet.http.HttpServletRequest;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;

import com.testingallprocedurescenarios.wmstudio.service.WMSTUDIOProcedureExecutorService;
import com.testingallprocedurescenarios.wmstudio.models.procedure.*;

@RestController(value = "WMSTUDIO.ProcedureExecutionController")
@RequestMapping("/WMSTUDIO/procedureExecutor")
@Api(value = "ProcedureExecutionController", description = "controller class for procedure execution")
public class ProcedureExecutionController {

    private static final Logger LOGGER = LoggerFactory.getLogger(ProcedureExecutionController.class);

    @Autowired
    private WMSTUDIOProcedureExecutorService procedureService;

    @RequestMapping(value = "/procedure/execute/Procedure_MultipleCursorData", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "Multiple Cursor Data")
    public ProcedureMultipleCursorDataResponse executeProcedure_MultipleCursorData(HttpServletRequest _request) {
        LOGGER.debug("Executing named procedure: Procedure_MultipleCursorData");
        ProcedureMultipleCursorDataResponse _result = procedureService.executeProcedure_MultipleCursorData();
        LOGGER.debug("got the result for named procedure: Procedure_MultipleCursorData, result:{}", _result);
        return _result;
    }

}