/*Generated by WaveMaker Studio*/
package com.testingallprocedurescenarios.school_db;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

public class SchoolEventsId implements Serializable {

    private Date scheduledDate;
    private String eventName;
    private Integer eventId;

    public Date getScheduledDate() {
        return this.scheduledDate;
    }

    public void setScheduledDate(Date scheduledDate) {
        this.scheduledDate = scheduledDate;
    }

    public String getEventName() {
        return this.eventName;
    }

    public void setEventName(String eventName) {
        this.eventName = eventName;
    }

    public Integer getEventId() {
        return this.eventId;
    }

    public void setEventId(Integer eventId) {
        this.eventId = eventId;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SchoolEvents)) return false;
        final SchoolEvents schoolEvents = (SchoolEvents) o;
        return Objects.equals(getScheduledDate(), schoolEvents.getScheduledDate()) &&
                Objects.equals(getEventName(), schoolEvents.getEventName()) &&
                Objects.equals(getEventId(), schoolEvents.getEventId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getScheduledDate(),
                getEventName(),
                getEventId());
    }
}