/*Generated by WaveMaker Studio*/
package com.testingallprocedurescenarios.school_db.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import com.testingallprocedurescenarios.school_db.models.procedure.*;

public interface School_DBProcedureExecutorService {

    Scenario3Response executeScenario3(Integer var);

    ProcedureBooleanResponse executeProcedure_Boolean(Boolean present);

    Scenario2Response executeScenario2(String academicyear);

    Scenario1Response executeScenario1(String academicyear);

    Scenario7Response executeScenario7(Integer var);

    Scenario6Response executeScenario6();

    Scenario5Response executeScenario5(String academicyear);

    Scenario4Response executeScenario4(String academicYear);

}