/*Generated by WaveMaker Studio*/
package com.testingallprocedurescenarios.dbscenarios.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Date;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;
import com.fasterxml.jackson.annotation.JsonView;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.wavemaker.commons.json.serializer.ByteArrayToStringSerializer;
import com.wavemaker.commons.json.views.JsonViews.BlobAsUrlView;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class HqlMysqlAllTypesWithAliasResponse implements Serializable {


    @ColumnAlias("PKID")
    private Integer pkid;

    @ColumnAlias("BYTECOL")
    private Short bytecol;

    @ColumnAlias("SHORTCOL")
    private Short shortcol;

    @ColumnAlias("DOUBLECOL")
    private Double doublecol;

    @ColumnAlias("LONGCOL")
    private BigInteger longcol;

    @ColumnAlias("FLOATCOL")
    private Float floatcol;

    @ColumnAlias("BIGINTCOL")
    private BigInteger bigintcol;

    @ColumnAlias("BIGDECCOL")
    private BigDecimal bigdeccol;

    @ColumnAlias("CHARCOL")
    private String charcol;

    @ColumnAlias("STRINGCOL")
    private String stringcol;

    @ColumnAlias("TEXTCOL")
    private String textcol;

    @ColumnAlias("CLOBCOL")
    private String clobcol;

    @ColumnAlias("DATECOL")
    private Date datecol;

    @ColumnAlias("TIMESTAMPCOL")
    private Date timestampcol;

    @ColumnAlias("BOOLEANCOL")
    private Boolean booleancol;

        @JsonView(BlobAsUrlView.class)
    @JsonSerialize(using = ByteArrayToStringSerializer.class)
    @JsonProperty(access = Access.READ_ONLY)
    @ColumnAlias("BLOBCOL")
    private byte[] blobcol;

    public Integer getPkid() {
        return this.pkid;
    }

    public void setPkid(Integer pkid) {
        this.pkid = pkid;
    }

    public Short getBytecol() {
        return this.bytecol;
    }

    public void setBytecol(Short bytecol) {
        this.bytecol = bytecol;
    }

    public Short getShortcol() {
        return this.shortcol;
    }

    public void setShortcol(Short shortcol) {
        this.shortcol = shortcol;
    }

    public Double getDoublecol() {
        return this.doublecol;
    }

    public void setDoublecol(Double doublecol) {
        this.doublecol = doublecol;
    }

    public BigInteger getLongcol() {
        return this.longcol;
    }

    public void setLongcol(BigInteger longcol) {
        this.longcol = longcol;
    }

    public Float getFloatcol() {
        return this.floatcol;
    }

    public void setFloatcol(Float floatcol) {
        this.floatcol = floatcol;
    }

    public BigInteger getBigintcol() {
        return this.bigintcol;
    }

    public void setBigintcol(BigInteger bigintcol) {
        this.bigintcol = bigintcol;
    }

    public BigDecimal getBigdeccol() {
        return this.bigdeccol;
    }

    public void setBigdeccol(BigDecimal bigdeccol) {
        this.bigdeccol = bigdeccol;
    }

    public String getCharcol() {
        return this.charcol;
    }

    public void setCharcol(String charcol) {
        this.charcol = charcol;
    }

    public String getStringcol() {
        return this.stringcol;
    }

    public void setStringcol(String stringcol) {
        this.stringcol = stringcol;
    }

    public String getTextcol() {
        return this.textcol;
    }

    public void setTextcol(String textcol) {
        this.textcol = textcol;
    }

    public String getClobcol() {
        return this.clobcol;
    }

    public void setClobcol(String clobcol) {
        this.clobcol = clobcol;
    }

    public Date getDatecol() {
        return this.datecol;
    }

    public void setDatecol(Date datecol) {
        this.datecol = datecol;
    }

    public Date getTimestampcol() {
        return this.timestampcol;
    }

    public void setTimestampcol(Date timestampcol) {
        this.timestampcol = timestampcol;
    }

    public Boolean getBooleancol() {
        return this.booleancol;
    }

    public void setBooleancol(Boolean booleancol) {
        this.booleancol = booleancol;
    }

    public byte[] getBlobcol() {
        return this.blobcol;
    }

    public void setBlobcol(byte[] blobcol) {
        this.blobcol = blobcol;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof HqlMysqlAllTypesWithAliasResponse)) return false;
        final HqlMysqlAllTypesWithAliasResponse hqlMysqlAllTypesWithAliasResponse = (HqlMysqlAllTypesWithAliasResponse) o;
        return Objects.equals(getPkid(), hqlMysqlAllTypesWithAliasResponse.getPkid()) &&
                Objects.equals(getBytecol(), hqlMysqlAllTypesWithAliasResponse.getBytecol()) &&
                Objects.equals(getShortcol(), hqlMysqlAllTypesWithAliasResponse.getShortcol()) &&
                Objects.equals(getDoublecol(), hqlMysqlAllTypesWithAliasResponse.getDoublecol()) &&
                Objects.equals(getLongcol(), hqlMysqlAllTypesWithAliasResponse.getLongcol()) &&
                Objects.equals(getFloatcol(), hqlMysqlAllTypesWithAliasResponse.getFloatcol()) &&
                Objects.equals(getBigintcol(), hqlMysqlAllTypesWithAliasResponse.getBigintcol()) &&
                Objects.equals(getBigdeccol(), hqlMysqlAllTypesWithAliasResponse.getBigdeccol()) &&
                Objects.equals(getCharcol(), hqlMysqlAllTypesWithAliasResponse.getCharcol()) &&
                Objects.equals(getStringcol(), hqlMysqlAllTypesWithAliasResponse.getStringcol()) &&
                Objects.equals(getTextcol(), hqlMysqlAllTypesWithAliasResponse.getTextcol()) &&
                Objects.equals(getClobcol(), hqlMysqlAllTypesWithAliasResponse.getClobcol()) &&
                Objects.equals(getDatecol(), hqlMysqlAllTypesWithAliasResponse.getDatecol()) &&
                Objects.equals(getTimestampcol(), hqlMysqlAllTypesWithAliasResponse.getTimestampcol()) &&
                Objects.equals(getBooleancol(), hqlMysqlAllTypesWithAliasResponse.getBooleancol()) &&
                Objects.equals(getBlobcol(), hqlMysqlAllTypesWithAliasResponse.getBlobcol());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPkid(),
                getBytecol(),
                getShortcol(),
                getDoublecol(),
                getLongcol(),
                getFloatcol(),
                getBigintcol(),
                getBigdeccol(),
                getCharcol(),
                getStringcol(),
                getTextcol(),
                getClobcol(),
                getDatecol(),
                getTimestampcol(),
                getBooleancol(),
                getBlobcol());
    }
}