/*Generated by WaveMaker Studio*/
package com.testingallprocedurescenarios.sample2.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcedureBonusIncrementsResponseContent implements Serializable {


    @ColumnAlias("WORKDEPT")
    private String workdept;

    @ColumnAlias("EMPNO")
    private String empno;

    @ColumnAlias("BONUS")
    private Float bonus;

    public String getWorkdept() {
        return this.workdept;
    }

    public void setWorkdept(String workdept) {
        this.workdept = workdept;
    }

    public String getEmpno() {
        return this.empno;
    }

    public void setEmpno(String empno) {
        this.empno = empno;
    }

    public Float getBonus() {
        return this.bonus;
    }

    public void setBonus(Float bonus) {
        this.bonus = bonus;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcedureBonusIncrementsResponseContent)) return false;
        final ProcedureBonusIncrementsResponseContent procedureBonusIncrementsResponseContent = (ProcedureBonusIncrementsResponseContent) o;
        return Objects.equals(getWorkdept(), procedureBonusIncrementsResponseContent.getWorkdept()) &&
                Objects.equals(getEmpno(), procedureBonusIncrementsResponseContent.getEmpno()) &&
                Objects.equals(getBonus(), procedureBonusIncrementsResponseContent.getBonus());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getWorkdept(),
                getEmpno(),
                getBonus());
    }
}