/*Generated by WaveMaker Studio*/
package com.testingallprocedurescenarios.sample2.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.servlet.http.HttpServletRequest;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;

import com.testingallprocedurescenarios.sample2.service.SAMPLE2ProcedureExecutorService;
import com.testingallprocedurescenarios.sample2.models.procedure.*;

@RestController(value = "SAMPLE2.ProcedureExecutionController")
@RequestMapping("/SAMPLE2/procedureExecutor")
@Api(value = "ProcedureExecutionController", description = "controller class for procedure execution")
public class ProcedureExecutionController {

    private static final Logger LOGGER = LoggerFactory.getLogger(ProcedureExecutionController.class);

    @Autowired
    private SAMPLE2ProcedureExecutorService procedureService;

    @RequestMapping(value = "/procedure/execute/Procedure_BonusIncrements", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "Bonus Increments")
    public ProcedureBonusIncrementsResponse executeProcedure_BonusIncrements(@RequestParam(value = "P_BONUSFACTOR") Integer pbonusfactor, @RequestParam(value = "P_BONUSMAXSUMFORDEPT") Integer pbonusmaxsumfordept, HttpServletRequest _request) {
        LOGGER.debug("Executing named procedure: Procedure_BonusIncrements");
        ProcedureBonusIncrementsResponse _result = procedureService.executeProcedure_BonusIncrements(pbonusfactor, pbonusmaxsumfordept);
        LOGGER.debug("got the result for named procedure: Procedure_BonusIncrements, result:{}", _result);
        return _result;
    }

    @RequestMapping(value = "/procedure/execute/Procedure_GetDeptDetailsById", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "Get Dept Details By deptId")
    public ProcedureGetDeptDetailsByIdResponse executeProcedure_GetDeptDetailsById(@RequestParam(value = "DEPTID") String deptid, HttpServletRequest _request) {
        LOGGER.debug("Executing named procedure: Procedure_GetDeptDetailsById");
        ProcedureGetDeptDetailsByIdResponse _result = procedureService.executeProcedure_GetDeptDetailsById(deptid);
        LOGGER.debug("got the result for named procedure: Procedure_GetDeptDetailsById, result:{}", _result);
        return _result;
    }

}