/*Generated by WaveMaker Studio*/
package com.testingallprocedurescenarios.dbscenarios;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigInteger;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DbtYpes generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`DBtYpes`")
public class DbtYpes implements Serializable {

    private Integer id;
    private Byte column2;
    private Long column3;
    private BigInteger column4;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`ID`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`COLUMN2`", nullable = true, scale = 0, precision = 3)
    public Byte getColumn2() {
        return this.column2;
    }

    public void setColumn2(Byte column2) {
        this.column2 = column2;
    }

    @Column(name = "`COLUMN3`", nullable = true, scale = 0, precision = 19)
    public Long getColumn3() {
        return this.column3;
    }

    public void setColumn3(Long column3) {
        this.column3 = column3;
    }

    @Column(name = "`COLUMN4`", nullable = true, scale = 0, precision = 19)
    public BigInteger getColumn4() {
        return this.column4;
    }

    public void setColumn4(BigInteger column4) {
        this.column4 = column4;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof DbtYpes)) return false;
        final DbtYpes dbtYpes = (DbtYpes) o;
        return Objects.equals(getId(), dbtYpes.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}