/*Generated by WaveMaker Studio*/
package com.testingallprocedurescenarios.db123__.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.sql.Date;
import java.util.List;
import java.util.Map;

import javax.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testingallprocedurescenarios.db123__.Table10;

/**
 * Service object for domain model class {@link Table10}.
 */
public interface Table10Service {

    /**
     * Creates a new Table10. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Table10 if any.
     *
     * @param table10 Details of the Table10 to be created; value cannot be null.
     * @return The newly created Table10.
     */
    Table10 create(@Valid Table10 table10);


	/**
     * Returns Table10 by given id if exists.
     *
     * @param table10Id The id of the Table10 to get; value cannot be null.
     * @return Table10 associated with the given table10Id.
	 * @throws EntityNotFoundException If no Table10 is found.
     */
    Table10 getById(Integer table10Id);

    /**
     * Find and return the Table10 by given id if exists, returns null otherwise.
     *
     * @param table10Id The id of the Table10 to get; value cannot be null.
     * @return Table10 associated with the given table10Id.
     */
    Table10 findById(Integer table10Id);

	/**
     * Find and return the list of Table10s by given id's.
     *
     * If orderedReturn true, the return List is ordered and positional relative to the incoming ids.
     *
     * In case of unknown entities:
     *
     * If enabled, A null is inserted into the List at the proper position(s).
     * If disabled, the nulls are not put into the return List.
     *
     * @param table10Ids The id's of the Table10 to get; value cannot be null.
     * @param orderedReturn Should the return List be ordered and positional in relation to the incoming ids?
     * @return Table10s associated with the given table10Ids.
     */
    List<Table10> findByMultipleIds(List<Integer> table10Ids, boolean orderedReturn);

    /**
     * Find and return the Table10 for given column3  if exists.
     *
     * @param column3 value of column3; value cannot be null.
     * @return Table10 associated with the given inputs.
     * @throws EntityNotFoundException if no matching Table10 found.
     */
    Table10 getByColumn3(Date column3);

    /**
     * Updates the details of an existing Table10. It replaces all fields of the existing Table10 with the given table10.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Table10 if any.
     *
     * @param table10 The details of the Table10 to be updated; value cannot be null.
     * @return The updated Table10.
     * @throws EntityNotFoundException if no Table10 is found with given input.
     */
    Table10 update(@Valid Table10 table10);

    /**
     * Deletes an existing Table10 with the given id.
     *
     * @param table10Id The id of the Table10 to be deleted; value cannot be null.
     * @return The deleted Table10.
     * @throws EntityNotFoundException if no Table10 found with the given id.
     */
    Table10 delete(Integer table10Id);

    /**
     * Deletes an existing Table10 with the given object.
     *
     * @param table10 The instance of the Table10 to be deleted; value cannot be null.
     */
    void delete(Table10 table10);

    /**
     * Find all Table10s matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
     *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
     *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Table10s.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
     */
    @Deprecated
    Page<Table10> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
     * Find all Table10s matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Table10s.
     *
     * @see Pageable
     * @see Page
     */
    Page<Table10> findAll(String query, Pageable pageable);

    /**
     * Exports all Table10s matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
     */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

    /**
     * Exports all Table10s matching the given input query to the given exportType format.
     *
     * @param options The export options provided by the user; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @param outputStream The output stream of the file for the exported data to be written to.
     *
     * @see DataExportOptions
     * @see Pageable
     * @see OutputStream
     */
    void export(DataExportOptions options, Pageable pageable, OutputStream outputStream);

    /**
     * Retrieve the count of the Table10s in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
     * @return The count of the Table10.
     */
    long count(String query);

    /**
     * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return Paginated data with included fields.
     *
     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
    Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}