/*Generated by WaveMaker Studio*/
package com.testingallprocedurescenarios.db123__.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testingallprocedurescenarios.db123__.TcOne2one;


/**
 * ServiceImpl object for domain model class TcOne2one.
 *
 * @see TcOne2one
 */
@Service("db123__.TcOne2oneService")
@Validated
public class TcOne2oneServiceImpl implements TcOne2oneService {

    private static final Logger LOGGER = LoggerFactory.getLogger(TcOne2oneServiceImpl.class);


    @Autowired
    @Qualifier("db123__.TcOne2oneDao")
    private WMGenericDao<TcOne2one, String> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<TcOne2one, String> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "db123__TransactionManager")
    @Override
    public TcOne2one create(TcOne2one tcOne2one) {
        LOGGER.debug("Creating a new TcOne2one with information: {}", tcOne2one);

        TcOne2one tcOne2oneCreated = this.wmGenericDao.create(tcOne2one);
        // reloading object from database to get database defined & server defined values.
        return this.wmGenericDao.refresh(tcOne2oneCreated);
    }

    @Transactional(readOnly = true, value = "db123__TransactionManager")
    @Override
    public TcOne2one getById(String tcone2oneId) {
        LOGGER.debug("Finding TcOne2one by id: {}", tcone2oneId);
        return this.wmGenericDao.findById(tcone2oneId);
    }

    @Transactional(readOnly = true, value = "db123__TransactionManager")
    @Override
    public TcOne2one findById(String tcone2oneId) {
        LOGGER.debug("Finding TcOne2one by id: {}", tcone2oneId);
        try {
            return this.wmGenericDao.findById(tcone2oneId);
        } catch (EntityNotFoundException ex) {
            LOGGER.debug("No TcOne2one found with id: {}", tcone2oneId, ex);
            return null;
        }
    }

    @Transactional(readOnly = true, value = "db123__TransactionManager")
    @Override
    public List<TcOne2one> findByMultipleIds(List<String> tcone2oneIds, boolean orderedReturn) {
        LOGGER.debug("Finding TcOne2ones by ids: {}", tcone2oneIds);

        return this.wmGenericDao.findByMultipleIds(tcone2oneIds, orderedReturn);
    }


    @Transactional(rollbackFor = EntityNotFoundException.class, value = "db123__TransactionManager")
    @Override
    public TcOne2one update(TcOne2one tcOne2one) {
        LOGGER.debug("Updating TcOne2one with information: {}", tcOne2one);

        this.wmGenericDao.update(tcOne2one);
        this.wmGenericDao.refresh(tcOne2one);

        return tcOne2one;
    }

    @Transactional(value = "db123__TransactionManager")
    @Override
    public TcOne2one delete(String tcone2oneId) {
        LOGGER.debug("Deleting TcOne2one with id: {}", tcone2oneId);
        TcOne2one deleted = this.wmGenericDao.findById(tcone2oneId);
        if (deleted == null) {
            LOGGER.debug("No TcOne2one found with id: {}", tcone2oneId);
            throw new EntityNotFoundException(String.valueOf(tcone2oneId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(value = "db123__TransactionManager")
    @Override
    public void delete(TcOne2one tcOne2one) {
        LOGGER.debug("Deleting TcOne2one with {}", tcOne2one);
        this.wmGenericDao.delete(tcOne2one);
    }

    @Transactional(readOnly = true, value = "db123__TransactionManager")
    @Override
    public Page<TcOne2one> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all TcOne2ones");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "db123__TransactionManager")
    @Override
    public Page<TcOne2one> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all TcOne2ones");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "db123__TransactionManager", timeout = 300)
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service db123__ for table TcOne2one to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

    @Transactional(readOnly = true, value = "db123__TransactionManager", timeout = 300)
    @Override
    public void export(DataExportOptions options, Pageable pageable, OutputStream outputStream) {
        LOGGER.debug("exporting data in the service db123__ for table TcOne2one to {} format", options.getExportType());
        this.wmGenericDao.export(options, pageable, outputStream);
    }

    @Transactional(readOnly = true, value = "db123__TransactionManager")
    @Override
    public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "db123__TransactionManager")
    @Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}