/*Generated by WaveMaker Studio*/
package com.testingallprocedurescenarios.db123__.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import javax.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testingallprocedurescenarios.db123__.TpOne2one;

/**
 * Service object for domain model class {@link TpOne2one}.
 */
public interface TpOne2oneService {

    /**
     * Creates a new TpOne2one. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on TpOne2one if any.
     *
     * @param tpOne2one Details of the TpOne2one to be created; value cannot be null.
     * @return The newly created TpOne2one.
     */
    TpOne2one create(@Valid TpOne2one tpOne2one);


	/**
     * Returns TpOne2one by given id if exists.
     *
     * @param tpone2oneId The id of the TpOne2one to get; value cannot be null.
     * @return TpOne2one associated with the given tpone2oneId.
	 * @throws EntityNotFoundException If no TpOne2one is found.
     */
    TpOne2one getById(String tpone2oneId);

    /**
     * Find and return the TpOne2one by given id if exists, returns null otherwise.
     *
     * @param tpone2oneId The id of the TpOne2one to get; value cannot be null.
     * @return TpOne2one associated with the given tpone2oneId.
     */
    TpOne2one findById(String tpone2oneId);

	/**
     * Find and return the list of TpOne2ones by given id's.
     *
     * If orderedReturn true, the return List is ordered and positional relative to the incoming ids.
     *
     * In case of unknown entities:
     *
     * If enabled, A null is inserted into the List at the proper position(s).
     * If disabled, the nulls are not put into the return List.
     *
     * @param tpone2oneIds The id's of the TpOne2one to get; value cannot be null.
     * @param orderedReturn Should the return List be ordered and positional in relation to the incoming ids?
     * @return TpOne2ones associated with the given tpone2oneIds.
     */
    List<TpOne2one> findByMultipleIds(List<String> tpone2oneIds, boolean orderedReturn);


    /**
     * Updates the details of an existing TpOne2one. It replaces all fields of the existing TpOne2one with the given tpOne2one.
     *
     * This method overrides the input field values using Server side or database managed properties defined on TpOne2one if any.
     *
     * @param tpOne2one The details of the TpOne2one to be updated; value cannot be null.
     * @return The updated TpOne2one.
     * @throws EntityNotFoundException if no TpOne2one is found with given input.
     */
    TpOne2one update(@Valid TpOne2one tpOne2one);

    /**
     * Deletes an existing TpOne2one with the given id.
     *
     * @param tpone2oneId The id of the TpOne2one to be deleted; value cannot be null.
     * @return The deleted TpOne2one.
     * @throws EntityNotFoundException if no TpOne2one found with the given id.
     */
    TpOne2one delete(String tpone2oneId);

    /**
     * Deletes an existing TpOne2one with the given object.
     *
     * @param tpOne2one The instance of the TpOne2one to be deleted; value cannot be null.
     */
    void delete(TpOne2one tpOne2one);

    /**
     * Find all TpOne2ones matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
     *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
     *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching TpOne2ones.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
     */
    @Deprecated
    Page<TpOne2one> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
     * Find all TpOne2ones matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching TpOne2ones.
     *
     * @see Pageable
     * @see Page
     */
    Page<TpOne2one> findAll(String query, Pageable pageable);

    /**
     * Exports all TpOne2ones matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
     */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

    /**
     * Exports all TpOne2ones matching the given input query to the given exportType format.
     *
     * @param options The export options provided by the user; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @param outputStream The output stream of the file for the exported data to be written to.
     *
     * @see DataExportOptions
     * @see Pageable
     * @see OutputStream
     */
    void export(DataExportOptions options, Pageable pageable, OutputStream outputStream);

    /**
     * Retrieve the count of the TpOne2ones in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
     * @return The count of the TpOne2one.
     */
    long count(String query);

    /**
     * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return Paginated data with included fields.
     *
     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
    Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}