/*Generated by WaveMaker Studio*/
package com.testingallprocedurescenarios.wmstudio.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ProcedureMultipleCursorDataResponseRegionsdata implements Serializable {


    @ColumnAlias("REGION_ID")
    private BigDecimal regionId;

    @ColumnAlias("REGION_NAME")
    private String regionName;

    public BigDecimal getRegionId() {
        return this.regionId;
    }

    public void setRegionId(BigDecimal regionId) {
        this.regionId = regionId;
    }

    public String getRegionName() {
        return this.regionName;
    }

    public void setRegionName(String regionName) {
        this.regionName = regionName;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ProcedureMultipleCursorDataResponseRegionsdata)) return false;
        final ProcedureMultipleCursorDataResponseRegionsdata procedureMultipleCursorDataResponseRegionsdata = (ProcedureMultipleCursorDataResponseRegionsdata) o;
        return Objects.equals(getRegionId(), procedureMultipleCursorDataResponseRegionsdata.getRegionId()) &&
                Objects.equals(getRegionName(), procedureMultipleCursorDataResponseRegionsdata.getRegionName());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getRegionId(),
                getRegionName());
    }
}