/*Generated by WaveMaker Studio*/
package com.testingallprocedurescenarios.adventureworks2014.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.export.ExportOptions;

import com.testingallprocedurescenarios.adventureworks2014.models.query.*;

public interface AdventureWorks2014QueryExecutorService {

    Page<SvGetPersonByPersonTypeResponse> executeSV_GetPersonByPersonType(String personType, Pageable pageable);

    void exportSV_GetPersonByPersonType(String personType, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    SvPersonSingleRecordResponse executeSV_PersonSingleRecord();

}