/*Generated by WaveMaker Studio*/
package com.testingallprocedurescenarios.adventureworks2014.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.sql.Date;

import com.testingallprocedurescenarios.adventureworks2014.models.procedure.*;

public interface AdventureWorks2014ProcedureExecutorService {

    ProcedureGetByHireDateResponse executeProcedure_GetByHireDate(Date empHireDate);

    Procedure1000nullTitlesResponse executeProcedure_1000NullTitles();

    ProcedureGetDeptDetailsResponse executeProcedure_getDeptDetails(Integer deptid);

    PorcedureDeptNameUsingIdResponse executePorcedure_DeptNameUsingID(Integer deptid);

}