/*Generated by WaveMaker Studio*/
package com.testingallprocedurescenarios.sample2.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testingallprocedurescenarios.sample2.EmpPhoto;
import com.testingallprocedurescenarios.sample2.EmpPhotoId;


/**
 * ServiceImpl object for domain model class EmpPhoto.
 *
 * @see EmpPhoto
 */
@Service("SAMPLE2.EmpPhotoService")
@Validated
public class EmpPhotoServiceImpl implements EmpPhotoService {

    private static final Logger LOGGER = LoggerFactory.getLogger(EmpPhotoServiceImpl.class);


    @Autowired
    @Qualifier("SAMPLE2.EmpPhotoDao")
    private WMGenericDao<EmpPhoto, EmpPhotoId> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<EmpPhoto, EmpPhotoId> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "SAMPLE2TransactionManager")
    @Override
    public EmpPhoto create(EmpPhoto empPhoto) {
        LOGGER.debug("Creating a new EmpPhoto with information: {}", empPhoto);

        EmpPhoto empPhotoCreated = this.wmGenericDao.create(empPhoto);
        // reloading object from database to get database defined & server defined values.
        return this.wmGenericDao.refresh(empPhotoCreated);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public EmpPhoto getById(EmpPhotoId empphotoId) {
        LOGGER.debug("Finding EmpPhoto by id: {}", empphotoId);
        return this.wmGenericDao.findById(empphotoId);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public EmpPhoto findById(EmpPhotoId empphotoId) {
        LOGGER.debug("Finding EmpPhoto by id: {}", empphotoId);
        try {
            return this.wmGenericDao.findById(empphotoId);
        } catch (EntityNotFoundException ex) {
            LOGGER.debug("No EmpPhoto found with id: {}", empphotoId, ex);
            return null;
        }
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public List<EmpPhoto> findByMultipleIds(List<EmpPhotoId> empphotoIds, boolean orderedReturn) {
        LOGGER.debug("Finding EmpPhotos by ids: {}", empphotoIds);

        return this.wmGenericDao.findByMultipleIds(empphotoIds, orderedReturn);
    }


    @Transactional(rollbackFor = EntityNotFoundException.class, value = "SAMPLE2TransactionManager")
    @Override
    public EmpPhoto update(EmpPhoto empPhoto) {
        LOGGER.debug("Updating EmpPhoto with information: {}", empPhoto);

        this.wmGenericDao.update(empPhoto);
        this.wmGenericDao.refresh(empPhoto);

        return empPhoto;
    }

    @Transactional(value = "SAMPLE2TransactionManager")
    @Override
    public EmpPhoto delete(EmpPhotoId empphotoId) {
        LOGGER.debug("Deleting EmpPhoto with id: {}", empphotoId);
        EmpPhoto deleted = this.wmGenericDao.findById(empphotoId);
        if (deleted == null) {
            LOGGER.debug("No EmpPhoto found with id: {}", empphotoId);
            throw new EntityNotFoundException(String.valueOf(empphotoId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(value = "SAMPLE2TransactionManager")
    @Override
    public void delete(EmpPhoto empPhoto) {
        LOGGER.debug("Deleting EmpPhoto with {}", empPhoto);
        this.wmGenericDao.delete(empPhoto);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public Page<EmpPhoto> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all EmpPhotos");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public Page<EmpPhoto> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all EmpPhotos");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager", timeout = 300)
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service SAMPLE2 for table EmpPhoto to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager", timeout = 300)
    @Override
    public void export(DataExportOptions options, Pageable pageable, OutputStream outputStream) {
        LOGGER.debug("exporting data in the service SAMPLE2 for table EmpPhoto to {} format", options.getExportType());
        this.wmGenericDao.export(options, pageable, outputStream);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}