/*Generated by WaveMaker Studio*/
package com.testingallprocedurescenarios.sample2.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testingallprocedurescenarios.sample2.EmpResume;
import com.testingallprocedurescenarios.sample2.EmpResumeId;


/**
 * ServiceImpl object for domain model class EmpResume.
 *
 * @see EmpResume
 */
@Service("SAMPLE2.EmpResumeService")
@Validated
public class EmpResumeServiceImpl implements EmpResumeService {

    private static final Logger LOGGER = LoggerFactory.getLogger(EmpResumeServiceImpl.class);


    @Autowired
    @Qualifier("SAMPLE2.EmpResumeDao")
    private WMGenericDao<EmpResume, EmpResumeId> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<EmpResume, EmpResumeId> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "SAMPLE2TransactionManager")
    @Override
    public EmpResume create(EmpResume empResume) {
        LOGGER.debug("Creating a new EmpResume with information: {}", empResume);

        EmpResume empResumeCreated = this.wmGenericDao.create(empResume);
        // reloading object from database to get database defined & server defined values.
        return this.wmGenericDao.refresh(empResumeCreated);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public EmpResume getById(EmpResumeId empresumeId) {
        LOGGER.debug("Finding EmpResume by id: {}", empresumeId);
        return this.wmGenericDao.findById(empresumeId);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public EmpResume findById(EmpResumeId empresumeId) {
        LOGGER.debug("Finding EmpResume by id: {}", empresumeId);
        try {
            return this.wmGenericDao.findById(empresumeId);
        } catch (EntityNotFoundException ex) {
            LOGGER.debug("No EmpResume found with id: {}", empresumeId, ex);
            return null;
        }
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public List<EmpResume> findByMultipleIds(List<EmpResumeId> empresumeIds, boolean orderedReturn) {
        LOGGER.debug("Finding EmpResumes by ids: {}", empresumeIds);

        return this.wmGenericDao.findByMultipleIds(empresumeIds, orderedReturn);
    }


    @Transactional(rollbackFor = EntityNotFoundException.class, value = "SAMPLE2TransactionManager")
    @Override
    public EmpResume update(EmpResume empResume) {
        LOGGER.debug("Updating EmpResume with information: {}", empResume);

        this.wmGenericDao.update(empResume);
        this.wmGenericDao.refresh(empResume);

        return empResume;
    }

    @Transactional(value = "SAMPLE2TransactionManager")
    @Override
    public EmpResume delete(EmpResumeId empresumeId) {
        LOGGER.debug("Deleting EmpResume with id: {}", empresumeId);
        EmpResume deleted = this.wmGenericDao.findById(empresumeId);
        if (deleted == null) {
            LOGGER.debug("No EmpResume found with id: {}", empresumeId);
            throw new EntityNotFoundException(String.valueOf(empresumeId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(value = "SAMPLE2TransactionManager")
    @Override
    public void delete(EmpResume empResume) {
        LOGGER.debug("Deleting EmpResume with {}", empResume);
        this.wmGenericDao.delete(empResume);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public Page<EmpResume> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all EmpResumes");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public Page<EmpResume> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all EmpResumes");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager", timeout = 300)
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service SAMPLE2 for table EmpResume to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager", timeout = 300)
    @Override
    public void export(DataExportOptions options, Pageable pageable, OutputStream outputStream) {
        LOGGER.debug("exporting data in the service SAMPLE2 for table EmpResume to {} format", options.getExportType());
        this.wmGenericDao.export(options, pageable, outputStream);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}