/*Generated by WaveMaker Studio*/
package com.testingallprocedurescenarios.sample2.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.IOException;
import java.io.OutputStream;
import java.math.BigInteger;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.ObjectReader;
import com.wavemaker.commons.InvalidInputException;
import com.wavemaker.commons.MessageResource;
import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testingallprocedurescenarios.sample2.Purchaseorder;


/**
 * ServiceImpl object for domain model class Purchaseorder.
 *
 * @see Purchaseorder
 */
@Service("SAMPLE2.PurchaseorderService")
@Validated
public class PurchaseorderServiceImpl implements PurchaseorderService {

    private static final Logger LOGGER = LoggerFactory.getLogger(PurchaseorderServiceImpl.class);


    @Autowired
    @Qualifier("SAMPLE2.PurchaseorderDao")
    private WMGenericDao<Purchaseorder, BigInteger> wmGenericDao;

    @Autowired
    private ObjectMapper objectMapper;


    public void setWMGenericDao(WMGenericDao<Purchaseorder, BigInteger> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "SAMPLE2TransactionManager")
    @Override
    public Purchaseorder create(Purchaseorder purchaseorder) {
        LOGGER.debug("Creating a new Purchaseorder with information: {}", purchaseorder);

        Purchaseorder purchaseorderCreated = this.wmGenericDao.create(purchaseorder);
        // reloading object from database to get database defined & server defined values.
        return this.wmGenericDao.refresh(purchaseorderCreated);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public Purchaseorder getById(BigInteger purchaseorderId) {
        LOGGER.debug("Finding Purchaseorder by id: {}", purchaseorderId);
        return this.wmGenericDao.findById(purchaseorderId);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public Purchaseorder findById(BigInteger purchaseorderId) {
        LOGGER.debug("Finding Purchaseorder by id: {}", purchaseorderId);
        try {
            return this.wmGenericDao.findById(purchaseorderId);
        } catch (EntityNotFoundException ex) {
            LOGGER.debug("No Purchaseorder found with id: {}", purchaseorderId, ex);
            return null;
        }
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public List<Purchaseorder> findByMultipleIds(List<BigInteger> purchaseorderIds, boolean orderedReturn) {
        LOGGER.debug("Finding Purchaseorders by ids: {}", purchaseorderIds);

        return this.wmGenericDao.findByMultipleIds(purchaseorderIds, orderedReturn);
    }


    @Transactional(rollbackFor = EntityNotFoundException.class, value = "SAMPLE2TransactionManager")
    @Override
    public Purchaseorder update(Purchaseorder purchaseorder) {
        LOGGER.debug("Updating Purchaseorder with information: {}", purchaseorder);

        this.wmGenericDao.update(purchaseorder);
        this.wmGenericDao.refresh(purchaseorder);

        return purchaseorder;
    }

    @Transactional(value = "SAMPLE2TransactionManager")
    @Override
    public Purchaseorder partialUpdate(BigInteger purchaseorderId, Map<String, Object>purchaseorderPatch) {
        LOGGER.debug("Partially Updating the Purchaseorder with id: {}", purchaseorderId);

        Purchaseorder purchaseorder = getById(purchaseorderId);

        try {
            ObjectReader purchaseorderReader = this.objectMapper.readerForUpdating(purchaseorder);
            purchaseorder = purchaseorderReader.readValue(this.objectMapper.writeValueAsString(purchaseorderPatch));
        } catch (IOException ex) {
            LOGGER.debug("There was a problem in applying the patch: {}", purchaseorderPatch, ex);
            throw new InvalidInputException("Could not apply patch",ex);
        }

        purchaseorder = update(purchaseorder);

        return purchaseorder;
    }

    @Transactional(value = "SAMPLE2TransactionManager")
    @Override
    public Purchaseorder delete(BigInteger purchaseorderId) {
        LOGGER.debug("Deleting Purchaseorder with id: {}", purchaseorderId);
        Purchaseorder deleted = this.wmGenericDao.findById(purchaseorderId);
        if (deleted == null) {
            LOGGER.debug("No Purchaseorder found with id: {}", purchaseorderId);
            throw new EntityNotFoundException(MessageResource.create("com.wavemaker.runtime.entity.not.found"), Purchaseorder.class.getSimpleName(), purchaseorderId);
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(value = "SAMPLE2TransactionManager")
    @Override
    public void delete(Purchaseorder purchaseorder) {
        LOGGER.debug("Deleting Purchaseorder with {}", purchaseorder);
        this.wmGenericDao.delete(purchaseorder);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public Page<Purchaseorder> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Purchaseorders");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public Page<Purchaseorder> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Purchaseorders");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager", timeout = 300)
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service SAMPLE2 for table Purchaseorder to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager", timeout = 300)
    @Override
    public void export(DataExportOptions options, Pageable pageable, OutputStream outputStream) {
        LOGGER.debug("exporting data in the service SAMPLE2 for table Purchaseorder to {} format", options.getExportType());
        this.wmGenericDao.export(options, pageable, outputStream);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}