/*Generated by WaveMaker Studio*/
package com.testingallprocedurescenarios.sample2.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.IOException;
import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.ObjectReader;
import com.wavemaker.commons.InvalidInputException;
import com.wavemaker.commons.MessageResource;
import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testingallprocedurescenarios.sample2.Staff;
import com.testingallprocedurescenarios.sample2.StaffId;


/**
 * ServiceImpl object for domain model class Staff.
 *
 * @see Staff
 */
@Service("SAMPLE2.StaffService")
@Validated
public class StaffServiceImpl implements StaffService {

    private static final Logger LOGGER = LoggerFactory.getLogger(StaffServiceImpl.class);


    @Autowired
    @Qualifier("SAMPLE2.StaffDao")
    private WMGenericDao<Staff, StaffId> wmGenericDao;

    @Autowired
    private ObjectMapper objectMapper;


    public void setWMGenericDao(WMGenericDao<Staff, StaffId> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "SAMPLE2TransactionManager")
    @Override
    public Staff create(Staff staff) {
        LOGGER.debug("Creating a new Staff with information: {}", staff);

        Staff staffCreated = this.wmGenericDao.create(staff);
        // reloading object from database to get database defined & server defined values.
        return this.wmGenericDao.refresh(staffCreated);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public Staff getById(StaffId staffId) {
        LOGGER.debug("Finding Staff by id: {}", staffId);
        return this.wmGenericDao.findById(staffId);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public Staff findById(StaffId staffId) {
        LOGGER.debug("Finding Staff by id: {}", staffId);
        try {
            return this.wmGenericDao.findById(staffId);
        } catch (EntityNotFoundException ex) {
            LOGGER.debug("No Staff found with id: {}", staffId, ex);
            return null;
        }
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public List<Staff> findByMultipleIds(List<StaffId> staffIds, boolean orderedReturn) {
        LOGGER.debug("Finding Staffs by ids: {}", staffIds);

        return this.wmGenericDao.findByMultipleIds(staffIds, orderedReturn);
    }


    @Transactional(rollbackFor = EntityNotFoundException.class, value = "SAMPLE2TransactionManager")
    @Override
    public Staff update(Staff staff) {
        LOGGER.debug("Updating Staff with information: {}", staff);

        this.wmGenericDao.update(staff);
        this.wmGenericDao.refresh(staff);

        return staff;
    }

    @Transactional(value = "SAMPLE2TransactionManager")
    @Override
    public Staff partialUpdate(StaffId staffId, Map<String, Object>staffPatch) {
        LOGGER.debug("Partially Updating the Staff with id: {}", staffId);

        Staff staff = getById(staffId);

        try {
            ObjectReader staffReader = this.objectMapper.readerForUpdating(staff);
            staff = staffReader.readValue(this.objectMapper.writeValueAsString(staffPatch));
        } catch (IOException ex) {
            LOGGER.debug("There was a problem in applying the patch: {}", staffPatch, ex);
            throw new InvalidInputException("Could not apply patch",ex);
        }

        staff = update(staff);

        return staff;
    }

    @Transactional(value = "SAMPLE2TransactionManager")
    @Override
    public Staff delete(StaffId staffId) {
        LOGGER.debug("Deleting Staff with id: {}", staffId);
        Staff deleted = this.wmGenericDao.findById(staffId);
        if (deleted == null) {
            LOGGER.debug("No Staff found with id: {}", staffId);
            throw new EntityNotFoundException(MessageResource.create("com.wavemaker.runtime.entity.not.found"), Staff.class.getSimpleName(), staffId);
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(value = "SAMPLE2TransactionManager")
    @Override
    public void delete(Staff staff) {
        LOGGER.debug("Deleting Staff with {}", staff);
        this.wmGenericDao.delete(staff);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public Page<Staff> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Staffs");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public Page<Staff> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Staffs");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager", timeout = 300)
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service SAMPLE2 for table Staff to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager", timeout = 300)
    @Override
    public void export(DataExportOptions options, Pageable pageable, OutputStream outputStream) {
        LOGGER.debug("exporting data in the service SAMPLE2 for table Staff to {} format", options.getExportType());
        this.wmGenericDao.export(options, pageable, outputStream);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}