/*Generated by WaveMaker Studio*/
package com.testingallprocedurescenarios.sample2.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import javax.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testingallprocedurescenarios.sample2.Vastrde1;
import com.testingallprocedurescenarios.sample2.Vastrde1Id;

/**
 * Service object for domain model class {@link Vastrde1}.
 */
public interface Vastrde1Service {

    /**
     * Creates a new Vastrde1. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Vastrde1 if any.
     *
     * @param vastrde1 Details of the Vastrde1 to be created; value cannot be null.
     * @return The newly created Vastrde1.
     */
    Vastrde1 create(@Valid Vastrde1 vastrde1);


	/**
     * Returns Vastrde1 by given id if exists.
     *
     * @param vastrde1Id The id of the Vastrde1 to get; value cannot be null.
     * @return Vastrde1 associated with the given vastrde1Id.
	 * @throws EntityNotFoundException If no Vastrde1 is found.
     */
    Vastrde1 getById(Vastrde1Id vastrde1Id);

    /**
     * Find and return the Vastrde1 by given id if exists, returns null otherwise.
     *
     * @param vastrde1Id The id of the Vastrde1 to get; value cannot be null.
     * @return Vastrde1 associated with the given vastrde1Id.
     */
    Vastrde1 findById(Vastrde1Id vastrde1Id);

	/**
     * Find and return the list of Vastrde1s by given id's.
     *
     * If orderedReturn true, the return List is ordered and positional relative to the incoming ids.
     *
     * In case of unknown entities:
     *
     * If enabled, A null is inserted into the List at the proper position(s).
     * If disabled, the nulls are not put into the return List.
     *
     * @param vastrde1Ids The id's of the Vastrde1 to get; value cannot be null.
     * @param orderedReturn Should the return List be ordered and positional in relation to the incoming ids?
     * @return Vastrde1s associated with the given vastrde1Ids.
     */
    List<Vastrde1> findByMultipleIds(List<Vastrde1Id> vastrde1Ids, boolean orderedReturn);


    /**
     * Updates the details of an existing Vastrde1. It replaces all fields of the existing Vastrde1 with the given vastrde1.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Vastrde1 if any.
     *
     * @param vastrde1 The details of the Vastrde1 to be updated; value cannot be null.
     * @return The updated Vastrde1.
     * @throws EntityNotFoundException if no Vastrde1 is found with given input.
     */
    Vastrde1 update(@Valid Vastrde1 vastrde1);


    /**
     * Partially updates the details of an existing Vastrde1. It updates only the
     * fields of the existing Vastrde1 which are passed in the vastrde1Patch.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Vastrde1 if any.
     *
     * @param vastrde1Id The id of the Vastrde1 to be deleted; value cannot be null.
     * @param vastrde1Patch The partial data of Vastrde1 which is supposed to be updated; value cannot be null.
     * @return The updated Vastrde1.
     * @throws EntityNotFoundException if no Vastrde1 is found with given input.
     */
    Vastrde1 partialUpdate(Vastrde1Id vastrde1Id, Map<String, Object> vastrde1Patch);

    /**
     * Deletes an existing Vastrde1 with the given id.
     *
     * @param vastrde1Id The id of the Vastrde1 to be deleted; value cannot be null.
     * @return The deleted Vastrde1.
     * @throws EntityNotFoundException if no Vastrde1 found with the given id.
     */
    Vastrde1 delete(Vastrde1Id vastrde1Id);

    /**
     * Deletes an existing Vastrde1 with the given object.
     *
     * @param vastrde1 The instance of the Vastrde1 to be deleted; value cannot be null.
     */
    void delete(Vastrde1 vastrde1);

    /**
     * Find all Vastrde1s matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
     *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
     *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Vastrde1s.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
     */
    @Deprecated
    Page<Vastrde1> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
     * Find all Vastrde1s matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Vastrde1s.
     *
     * @see Pageable
     * @see Page
     */
    Page<Vastrde1> findAll(String query, Pageable pageable);

    /**
     * Exports all Vastrde1s matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
     */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

    /**
     * Exports all Vastrde1s matching the given input query to the given exportType format.
     *
     * @param options The export options provided by the user; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @param outputStream The output stream of the file for the exported data to be written to.
     *
     * @see DataExportOptions
     * @see Pageable
     * @see OutputStream
     */
    void export(DataExportOptions options, Pageable pageable, OutputStream outputStream);

    /**
     * Retrieve the count of the Vastrde1s in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
     * @return The count of the Vastrde1.
     */
    long count(String query);

    /**
     * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return Paginated data with included fields.
     *
     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
    Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}