/*Generated by WaveMaker Studio*/
package com.testingallprocedurescenarios.sample2.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testingallprocedurescenarios.sample2.Vastrde2;
import com.testingallprocedurescenarios.sample2.Vastrde2Id;


/**
 * ServiceImpl object for domain model class Vastrde2.
 *
 * @see Vastrde2
 */
@Service("SAMPLE2.Vastrde2Service")
@Validated
public class Vastrde2ServiceImpl implements Vastrde2Service {

    private static final Logger LOGGER = LoggerFactory.getLogger(Vastrde2ServiceImpl.class);


    @Autowired
    @Qualifier("SAMPLE2.Vastrde2Dao")
    private WMGenericDao<Vastrde2, Vastrde2Id> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<Vastrde2, Vastrde2Id> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "SAMPLE2TransactionManager")
    @Override
    public Vastrde2 create(Vastrde2 vastrde2) {
        LOGGER.debug("Creating a new Vastrde2 with information: {}", vastrde2);

        Vastrde2 vastrde2Created = this.wmGenericDao.create(vastrde2);
        // reloading object from database to get database defined & server defined values.
        return this.wmGenericDao.refresh(vastrde2Created);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public Vastrde2 getById(Vastrde2Id vastrde2Id) {
        LOGGER.debug("Finding Vastrde2 by id: {}", vastrde2Id);
        return this.wmGenericDao.findById(vastrde2Id);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public Vastrde2 findById(Vastrde2Id vastrde2Id) {
        LOGGER.debug("Finding Vastrde2 by id: {}", vastrde2Id);
        try {
            return this.wmGenericDao.findById(vastrde2Id);
        } catch (EntityNotFoundException ex) {
            LOGGER.debug("No Vastrde2 found with id: {}", vastrde2Id, ex);
            return null;
        }
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public List<Vastrde2> findByMultipleIds(List<Vastrde2Id> vastrde2Ids, boolean orderedReturn) {
        LOGGER.debug("Finding Vastrde2s by ids: {}", vastrde2Ids);

        return this.wmGenericDao.findByMultipleIds(vastrde2Ids, orderedReturn);
    }


    @Transactional(rollbackFor = EntityNotFoundException.class, value = "SAMPLE2TransactionManager")
    @Override
    public Vastrde2 update(Vastrde2 vastrde2) {
        LOGGER.debug("Updating Vastrde2 with information: {}", vastrde2);

        this.wmGenericDao.update(vastrde2);
        this.wmGenericDao.refresh(vastrde2);

        return vastrde2;
    }

    @Transactional(value = "SAMPLE2TransactionManager")
    @Override
    public Vastrde2 delete(Vastrde2Id vastrde2Id) {
        LOGGER.debug("Deleting Vastrde2 with id: {}", vastrde2Id);
        Vastrde2 deleted = this.wmGenericDao.findById(vastrde2Id);
        if (deleted == null) {
            LOGGER.debug("No Vastrde2 found with id: {}", vastrde2Id);
            throw new EntityNotFoundException(String.valueOf(vastrde2Id));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(value = "SAMPLE2TransactionManager")
    @Override
    public void delete(Vastrde2 vastrde2) {
        LOGGER.debug("Deleting Vastrde2 with {}", vastrde2);
        this.wmGenericDao.delete(vastrde2);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public Page<Vastrde2> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Vastrde2s");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public Page<Vastrde2> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Vastrde2s");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager", timeout = 300)
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service SAMPLE2 for table Vastrde2 to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager", timeout = 300)
    @Override
    public void export(DataExportOptions options, Pageable pageable, OutputStream outputStream) {
        LOGGER.debug("exporting data in the service SAMPLE2 for table Vastrde2 to {} format", options.getExportType());
        this.wmGenericDao.export(options, pageable, outputStream);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}