/*Generated by WaveMaker Studio*/
package com.testingallprocedurescenarios.sample2.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import javax.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testingallprocedurescenarios.sample2.Vempdpt1;
import com.testingallprocedurescenarios.sample2.Vempdpt1Id;

/**
 * Service object for domain model class {@link Vempdpt1}.
 */
public interface Vempdpt1Service {

    /**
     * Creates a new Vempdpt1. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Vempdpt1 if any.
     *
     * @param vempdpt1 Details of the Vempdpt1 to be created; value cannot be null.
     * @return The newly created Vempdpt1.
     */
    Vempdpt1 create(@Valid Vempdpt1 vempdpt1);


	/**
     * Returns Vempdpt1 by given id if exists.
     *
     * @param vempdpt1Id The id of the Vempdpt1 to get; value cannot be null.
     * @return Vempdpt1 associated with the given vempdpt1Id.
	 * @throws EntityNotFoundException If no Vempdpt1 is found.
     */
    Vempdpt1 getById(Vempdpt1Id vempdpt1Id);

    /**
     * Find and return the Vempdpt1 by given id if exists, returns null otherwise.
     *
     * @param vempdpt1Id The id of the Vempdpt1 to get; value cannot be null.
     * @return Vempdpt1 associated with the given vempdpt1Id.
     */
    Vempdpt1 findById(Vempdpt1Id vempdpt1Id);

	/**
     * Find and return the list of Vempdpt1s by given id's.
     *
     * If orderedReturn true, the return List is ordered and positional relative to the incoming ids.
     *
     * In case of unknown entities:
     *
     * If enabled, A null is inserted into the List at the proper position(s).
     * If disabled, the nulls are not put into the return List.
     *
     * @param vempdpt1Ids The id's of the Vempdpt1 to get; value cannot be null.
     * @param orderedReturn Should the return List be ordered and positional in relation to the incoming ids?
     * @return Vempdpt1s associated with the given vempdpt1Ids.
     */
    List<Vempdpt1> findByMultipleIds(List<Vempdpt1Id> vempdpt1Ids, boolean orderedReturn);


    /**
     * Updates the details of an existing Vempdpt1. It replaces all fields of the existing Vempdpt1 with the given vempdpt1.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Vempdpt1 if any.
     *
     * @param vempdpt1 The details of the Vempdpt1 to be updated; value cannot be null.
     * @return The updated Vempdpt1.
     * @throws EntityNotFoundException if no Vempdpt1 is found with given input.
     */
    Vempdpt1 update(@Valid Vempdpt1 vempdpt1);


    /**
     * Partially updates the details of an existing Vempdpt1. It updates only the
     * fields of the existing Vempdpt1 which are passed in the vempdpt1Patch.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Vempdpt1 if any.
     *
     * @param vempdpt1Id The id of the Vempdpt1 to be deleted; value cannot be null.
     * @param vempdpt1Patch The partial data of Vempdpt1 which is supposed to be updated; value cannot be null.
     * @return The updated Vempdpt1.
     * @throws EntityNotFoundException if no Vempdpt1 is found with given input.
     */
    Vempdpt1 partialUpdate(Vempdpt1Id vempdpt1Id, Map<String, Object> vempdpt1Patch);

    /**
     * Deletes an existing Vempdpt1 with the given id.
     *
     * @param vempdpt1Id The id of the Vempdpt1 to be deleted; value cannot be null.
     * @return The deleted Vempdpt1.
     * @throws EntityNotFoundException if no Vempdpt1 found with the given id.
     */
    Vempdpt1 delete(Vempdpt1Id vempdpt1Id);

    /**
     * Deletes an existing Vempdpt1 with the given object.
     *
     * @param vempdpt1 The instance of the Vempdpt1 to be deleted; value cannot be null.
     */
    void delete(Vempdpt1 vempdpt1);

    /**
     * Find all Vempdpt1s matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
     *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
     *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Vempdpt1s.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
     */
    @Deprecated
    Page<Vempdpt1> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
     * Find all Vempdpt1s matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Vempdpt1s.
     *
     * @see Pageable
     * @see Page
     */
    Page<Vempdpt1> findAll(String query, Pageable pageable);

    /**
     * Exports all Vempdpt1s matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
     */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

    /**
     * Exports all Vempdpt1s matching the given input query to the given exportType format.
     *
     * @param options The export options provided by the user; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @param outputStream The output stream of the file for the exported data to be written to.
     *
     * @see DataExportOptions
     * @see Pageable
     * @see OutputStream
     */
    void export(DataExportOptions options, Pageable pageable, OutputStream outputStream);

    /**
     * Retrieve the count of the Vempdpt1s in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
     * @return The count of the Vempdpt1.
     */
    long count(String query);

    /**
     * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return Paginated data with included fields.
     *
     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
    Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}