/*Generated by WaveMaker Studio*/
package com.testingallprocedurescenarios.sample2.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testingallprocedurescenarios.sample2.Vemp;
import com.testingallprocedurescenarios.sample2.VempId;


/**
 * ServiceImpl object for domain model class Vemp.
 *
 * @see Vemp
 */
@Service("SAMPLE2.VempService")
@Validated
public class VempServiceImpl implements VempService {

    private static final Logger LOGGER = LoggerFactory.getLogger(VempServiceImpl.class);


    @Autowired
    @Qualifier("SAMPLE2.VempDao")
    private WMGenericDao<Vemp, VempId> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<Vemp, VempId> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "SAMPLE2TransactionManager")
    @Override
    public Vemp create(Vemp vemp) {
        LOGGER.debug("Creating a new Vemp with information: {}", vemp);

        Vemp vempCreated = this.wmGenericDao.create(vemp);
        // reloading object from database to get database defined & server defined values.
        return this.wmGenericDao.refresh(vempCreated);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public Vemp getById(VempId vempId) {
        LOGGER.debug("Finding Vemp by id: {}", vempId);
        return this.wmGenericDao.findById(vempId);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public Vemp findById(VempId vempId) {
        LOGGER.debug("Finding Vemp by id: {}", vempId);
        try {
            return this.wmGenericDao.findById(vempId);
        } catch (EntityNotFoundException ex) {
            LOGGER.debug("No Vemp found with id: {}", vempId, ex);
            return null;
        }
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public List<Vemp> findByMultipleIds(List<VempId> vempIds, boolean orderedReturn) {
        LOGGER.debug("Finding Vemps by ids: {}", vempIds);

        return this.wmGenericDao.findByMultipleIds(vempIds, orderedReturn);
    }


    @Transactional(rollbackFor = EntityNotFoundException.class, value = "SAMPLE2TransactionManager")
    @Override
    public Vemp update(Vemp vemp) {
        LOGGER.debug("Updating Vemp with information: {}", vemp);

        this.wmGenericDao.update(vemp);
        this.wmGenericDao.refresh(vemp);

        return vemp;
    }

    @Transactional(value = "SAMPLE2TransactionManager")
    @Override
    public Vemp delete(VempId vempId) {
        LOGGER.debug("Deleting Vemp with id: {}", vempId);
        Vemp deleted = this.wmGenericDao.findById(vempId);
        if (deleted == null) {
            LOGGER.debug("No Vemp found with id: {}", vempId);
            throw new EntityNotFoundException(String.valueOf(vempId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(value = "SAMPLE2TransactionManager")
    @Override
    public void delete(Vemp vemp) {
        LOGGER.debug("Deleting Vemp with {}", vemp);
        this.wmGenericDao.delete(vemp);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public Page<Vemp> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Vemps");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public Page<Vemp> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Vemps");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager", timeout = 300)
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service SAMPLE2 for table Vemp to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager", timeout = 300)
    @Override
    public void export(DataExportOptions options, Pageable pageable, OutputStream outputStream) {
        LOGGER.debug("exporting data in the service SAMPLE2 for table Vemp to {} format", options.getExportType());
        this.wmGenericDao.export(options, pageable, outputStream);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}