/*Generated by WaveMaker Studio*/
package com.testingallprocedurescenarios.sample2.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.IOException;
import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.ObjectReader;
import com.wavemaker.commons.InvalidInputException;
import com.wavemaker.commons.MessageResource;
import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testingallprocedurescenarios.sample2.Vhdept;
import com.testingallprocedurescenarios.sample2.VhdeptId;


/**
 * ServiceImpl object for domain model class Vhdept.
 *
 * @see Vhdept
 */
@Service("SAMPLE2.VhdeptService")
@Validated
public class VhdeptServiceImpl implements VhdeptService {

    private static final Logger LOGGER = LoggerFactory.getLogger(VhdeptServiceImpl.class);


    @Autowired
    @Qualifier("SAMPLE2.VhdeptDao")
    private WMGenericDao<Vhdept, VhdeptId> wmGenericDao;

    @Autowired
    private ObjectMapper objectMapper;


    public void setWMGenericDao(WMGenericDao<Vhdept, VhdeptId> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "SAMPLE2TransactionManager")
    @Override
    public Vhdept create(Vhdept vhdept) {
        LOGGER.debug("Creating a new Vhdept with information: {}", vhdept);

        Vhdept vhdeptCreated = this.wmGenericDao.create(vhdept);
        // reloading object from database to get database defined & server defined values.
        return this.wmGenericDao.refresh(vhdeptCreated);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public Vhdept getById(VhdeptId vhdeptId) {
        LOGGER.debug("Finding Vhdept by id: {}", vhdeptId);
        return this.wmGenericDao.findById(vhdeptId);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public Vhdept findById(VhdeptId vhdeptId) {
        LOGGER.debug("Finding Vhdept by id: {}", vhdeptId);
        try {
            return this.wmGenericDao.findById(vhdeptId);
        } catch (EntityNotFoundException ex) {
            LOGGER.debug("No Vhdept found with id: {}", vhdeptId, ex);
            return null;
        }
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public List<Vhdept> findByMultipleIds(List<VhdeptId> vhdeptIds, boolean orderedReturn) {
        LOGGER.debug("Finding Vhdepts by ids: {}", vhdeptIds);

        return this.wmGenericDao.findByMultipleIds(vhdeptIds, orderedReturn);
    }


    @Transactional(rollbackFor = EntityNotFoundException.class, value = "SAMPLE2TransactionManager")
    @Override
    public Vhdept update(Vhdept vhdept) {
        LOGGER.debug("Updating Vhdept with information: {}", vhdept);

        this.wmGenericDao.update(vhdept);
        this.wmGenericDao.refresh(vhdept);

        return vhdept;
    }

    @Transactional(value = "SAMPLE2TransactionManager")
    @Override
    public Vhdept partialUpdate(VhdeptId vhdeptId, Map<String, Object>vhdeptPatch) {
        LOGGER.debug("Partially Updating the Vhdept with id: {}", vhdeptId);

        Vhdept vhdept = getById(vhdeptId);

        try {
            ObjectReader vhdeptReader = this.objectMapper.readerForUpdating(vhdept);
            vhdept = vhdeptReader.readValue(this.objectMapper.writeValueAsString(vhdeptPatch));
        } catch (IOException ex) {
            LOGGER.debug("There was a problem in applying the patch: {}", vhdeptPatch, ex);
            throw new InvalidInputException("Could not apply patch",ex);
        }

        vhdept = update(vhdept);

        return vhdept;
    }

    @Transactional(value = "SAMPLE2TransactionManager")
    @Override
    public Vhdept delete(VhdeptId vhdeptId) {
        LOGGER.debug("Deleting Vhdept with id: {}", vhdeptId);
        Vhdept deleted = this.wmGenericDao.findById(vhdeptId);
        if (deleted == null) {
            LOGGER.debug("No Vhdept found with id: {}", vhdeptId);
            throw new EntityNotFoundException(MessageResource.create("com.wavemaker.runtime.entity.not.found"), Vhdept.class.getSimpleName(), vhdeptId);
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(value = "SAMPLE2TransactionManager")
    @Override
    public void delete(Vhdept vhdept) {
        LOGGER.debug("Deleting Vhdept with {}", vhdept);
        this.wmGenericDao.delete(vhdept);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public Page<Vhdept> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Vhdepts");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public Page<Vhdept> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Vhdepts");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager", timeout = 300)
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service SAMPLE2 for table Vhdept to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager", timeout = 300)
    @Override
    public void export(DataExportOptions options, Pageable pageable, OutputStream outputStream) {
        LOGGER.debug("exporting data in the service SAMPLE2 for table Vhdept to {} format", options.getExportType());
        this.wmGenericDao.export(options, pageable, outputStream);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}