/*Generated by WaveMaker Studio*/
package com.testingallprocedurescenarios.sample2.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testingallprocedurescenarios.sample2.Vpstrde1;
import com.testingallprocedurescenarios.sample2.Vpstrde1Id;


/**
 * ServiceImpl object for domain model class Vpstrde1.
 *
 * @see Vpstrde1
 */
@Service("SAMPLE2.Vpstrde1Service")
@Validated
public class Vpstrde1ServiceImpl implements Vpstrde1Service {

    private static final Logger LOGGER = LoggerFactory.getLogger(Vpstrde1ServiceImpl.class);


    @Autowired
    @Qualifier("SAMPLE2.Vpstrde1Dao")
    private WMGenericDao<Vpstrde1, Vpstrde1Id> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<Vpstrde1, Vpstrde1Id> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "SAMPLE2TransactionManager")
    @Override
    public Vpstrde1 create(Vpstrde1 vpstrde1) {
        LOGGER.debug("Creating a new Vpstrde1 with information: {}", vpstrde1);

        Vpstrde1 vpstrde1Created = this.wmGenericDao.create(vpstrde1);
        // reloading object from database to get database defined & server defined values.
        return this.wmGenericDao.refresh(vpstrde1Created);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public Vpstrde1 getById(Vpstrde1Id vpstrde1Id) {
        LOGGER.debug("Finding Vpstrde1 by id: {}", vpstrde1Id);
        return this.wmGenericDao.findById(vpstrde1Id);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public Vpstrde1 findById(Vpstrde1Id vpstrde1Id) {
        LOGGER.debug("Finding Vpstrde1 by id: {}", vpstrde1Id);
        try {
            return this.wmGenericDao.findById(vpstrde1Id);
        } catch (EntityNotFoundException ex) {
            LOGGER.debug("No Vpstrde1 found with id: {}", vpstrde1Id, ex);
            return null;
        }
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public List<Vpstrde1> findByMultipleIds(List<Vpstrde1Id> vpstrde1Ids, boolean orderedReturn) {
        LOGGER.debug("Finding Vpstrde1s by ids: {}", vpstrde1Ids);

        return this.wmGenericDao.findByMultipleIds(vpstrde1Ids, orderedReturn);
    }


    @Transactional(rollbackFor = EntityNotFoundException.class, value = "SAMPLE2TransactionManager")
    @Override
    public Vpstrde1 update(Vpstrde1 vpstrde1) {
        LOGGER.debug("Updating Vpstrde1 with information: {}", vpstrde1);

        this.wmGenericDao.update(vpstrde1);
        this.wmGenericDao.refresh(vpstrde1);

        return vpstrde1;
    }

    @Transactional(value = "SAMPLE2TransactionManager")
    @Override
    public Vpstrde1 delete(Vpstrde1Id vpstrde1Id) {
        LOGGER.debug("Deleting Vpstrde1 with id: {}", vpstrde1Id);
        Vpstrde1 deleted = this.wmGenericDao.findById(vpstrde1Id);
        if (deleted == null) {
            LOGGER.debug("No Vpstrde1 found with id: {}", vpstrde1Id);
            throw new EntityNotFoundException(String.valueOf(vpstrde1Id));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(value = "SAMPLE2TransactionManager")
    @Override
    public void delete(Vpstrde1 vpstrde1) {
        LOGGER.debug("Deleting Vpstrde1 with {}", vpstrde1);
        this.wmGenericDao.delete(vpstrde1);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public Page<Vpstrde1> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Vpstrde1s");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public Page<Vpstrde1> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Vpstrde1s");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager", timeout = 300)
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service SAMPLE2 for table Vpstrde1 to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager", timeout = 300)
    @Override
    public void export(DataExportOptions options, Pageable pageable, OutputStream outputStream) {
        LOGGER.debug("exporting data in the service SAMPLE2 for table Vpstrde1 to {} format", options.getExportType());
        this.wmGenericDao.export(options, pageable, outputStream);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "SAMPLE2TransactionManager")
    @Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}