/*Generated by WaveMaker Studio*/
package com.testingallprocedurescenarios.dbscenarios.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import javax.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testingallprocedurescenarios.dbscenarios.AutoWireProcedure1000nullTitles;

/**
 * Service object for domain model class {@link AutoWireProcedure1000nullTitles}.
 */
public interface AutoWireProcedure1000nullTitlesService {

    /**
     * Creates a new AutoWireProcedure1000nullTitles. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on AutoWireProcedure1000nullTitles if any.
     *
     * @param autoWireProcedure1000nullTitles Details of the AutoWireProcedure1000nullTitles to be created; value cannot be null.
     * @return The newly created AutoWireProcedure1000nullTitles.
     */
    AutoWireProcedure1000nullTitles create(@Valid AutoWireProcedure1000nullTitles autoWireProcedure1000nullTitles);


	/**
     * Returns AutoWireProcedure1000nullTitles by given id if exists.
     *
     * @param autowireprocedure1000nulltitlesId The id of the AutoWireProcedure1000nullTitles to get; value cannot be null.
     * @return AutoWireProcedure1000nullTitles associated with the given autowireprocedure1000nulltitlesId.
	 * @throws EntityNotFoundException If no AutoWireProcedure1000nullTitles is found.
     */
    AutoWireProcedure1000nullTitles getById(Long autowireprocedure1000nulltitlesId);

    /**
     * Find and return the AutoWireProcedure1000nullTitles by given id if exists, returns null otherwise.
     *
     * @param autowireprocedure1000nulltitlesId The id of the AutoWireProcedure1000nullTitles to get; value cannot be null.
     * @return AutoWireProcedure1000nullTitles associated with the given autowireprocedure1000nulltitlesId.
     */
    AutoWireProcedure1000nullTitles findById(Long autowireprocedure1000nulltitlesId);

	/**
     * Find and return the list of AutoWireProcedure1000nullTitles by given id's.
     *
     * If orderedReturn true, the return List is ordered and positional relative to the incoming ids.
     *
     * In case of unknown entities:
     *
     * If enabled, A null is inserted into the List at the proper position(s).
     * If disabled, the nulls are not put into the return List.
     *
     * @param autowireprocedure1000nulltitlesIds The id's of the AutoWireProcedure1000nullTitles to get; value cannot be null.
     * @param orderedReturn Should the return List be ordered and positional in relation to the incoming ids?
     * @return AutoWireProcedure1000nullTitles associated with the given autowireprocedure1000nulltitlesIds.
     */
    List<AutoWireProcedure1000nullTitles> findByMultipleIds(List<Long> autowireprocedure1000nulltitlesIds, boolean orderedReturn);


    /**
     * Updates the details of an existing AutoWireProcedure1000nullTitles. It replaces all fields of the existing AutoWireProcedure1000nullTitles with the given autoWireProcedure1000nullTitles.
     *
     * This method overrides the input field values using Server side or database managed properties defined on AutoWireProcedure1000nullTitles if any.
     *
     * @param autoWireProcedure1000nullTitles The details of the AutoWireProcedure1000nullTitles to be updated; value cannot be null.
     * @return The updated AutoWireProcedure1000nullTitles.
     * @throws EntityNotFoundException if no AutoWireProcedure1000nullTitles is found with given input.
     */
    AutoWireProcedure1000nullTitles update(@Valid AutoWireProcedure1000nullTitles autoWireProcedure1000nullTitles);


    /**
     * Partially updates the details of an existing AutoWireProcedure1000nullTitles. It updates only the
     * fields of the existing AutoWireProcedure1000nullTitles which are passed in the autoWireProcedure1000nullTitlesPatch.
     *
     * This method overrides the input field values using Server side or database managed properties defined on AutoWireProcedure1000nullTitles if any.
     *
     * @param autowireprocedure1000nulltitlesId The id of the AutoWireProcedure1000nullTitles to be deleted; value cannot be null.
     * @param autoWireProcedure1000nullTitlesPatch The partial data of AutoWireProcedure1000nullTitles which is supposed to be updated; value cannot be null.
     * @return The updated AutoWireProcedure1000nullTitles.
     * @throws EntityNotFoundException if no AutoWireProcedure1000nullTitles is found with given input.
     */
    AutoWireProcedure1000nullTitles partialUpdate(Long autowireprocedure1000nulltitlesId, Map<String, Object> autoWireProcedure1000nullTitlesPatch);

    /**
     * Deletes an existing AutoWireProcedure1000nullTitles with the given id.
     *
     * @param autowireprocedure1000nulltitlesId The id of the AutoWireProcedure1000nullTitles to be deleted; value cannot be null.
     * @return The deleted AutoWireProcedure1000nullTitles.
     * @throws EntityNotFoundException if no AutoWireProcedure1000nullTitles found with the given id.
     */
    AutoWireProcedure1000nullTitles delete(Long autowireprocedure1000nulltitlesId);

    /**
     * Deletes an existing AutoWireProcedure1000nullTitles with the given object.
     *
     * @param autoWireProcedure1000nullTitles The instance of the AutoWireProcedure1000nullTitles to be deleted; value cannot be null.
     */
    void delete(AutoWireProcedure1000nullTitles autoWireProcedure1000nullTitles);

    /**
     * Find all AutoWireProcedure1000nullTitles matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
     *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
     *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching AutoWireProcedure1000nullTitles.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
     */
    @Deprecated
    Page<AutoWireProcedure1000nullTitles> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
     * Find all AutoWireProcedure1000nullTitles matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching AutoWireProcedure1000nullTitles.
     *
     * @see Pageable
     * @see Page
     */
    Page<AutoWireProcedure1000nullTitles> findAll(String query, Pageable pageable);

    /**
     * Exports all AutoWireProcedure1000nullTitles matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
     */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

    /**
     * Exports all AutoWireProcedure1000nullTitles matching the given input query to the given exportType format.
     *
     * @param options The export options provided by the user; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @param outputStream The output stream of the file for the exported data to be written to.
     *
     * @see DataExportOptions
     * @see Pageable
     * @see OutputStream
     */
    void export(DataExportOptions options, Pageable pageable, OutputStream outputStream);

    /**
     * Retrieve the count of the AutoWireProcedure1000nullTitles in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
     * @return The count of the AutoWireProcedure1000nullTitles.
     */
    long count(String query);

    /**
     * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return Paginated data with included fields.
     *
     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
    Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}