/*Generated by WaveMaker Studio*/
package com.testingallprocedurescenarios.dbscenarios.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import javax.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testingallprocedurescenarios.dbscenarios.ZeroAsPk;

/**
 * Service object for domain model class {@link ZeroAsPk}.
 */
public interface ZeroAsPkService {

    /**
     * Creates a new ZeroAsPk. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on ZeroAsPk if any.
     *
     * @param zeroAsPk Details of the ZeroAsPk to be created; value cannot be null.
     * @return The newly created ZeroAsPk.
     */
    ZeroAsPk create(@Valid ZeroAsPk zeroAsPk);


	/**
     * Returns ZeroAsPk by given id if exists.
     *
     * @param zeroaspkId The id of the ZeroAsPk to get; value cannot be null.
     * @return ZeroAsPk associated with the given zeroaspkId.
	 * @throws EntityNotFoundException If no ZeroAsPk is found.
     */
    ZeroAsPk getById(Integer zeroaspkId);

    /**
     * Find and return the ZeroAsPk by given id if exists, returns null otherwise.
     *
     * @param zeroaspkId The id of the ZeroAsPk to get; value cannot be null.
     * @return ZeroAsPk associated with the given zeroaspkId.
     */
    ZeroAsPk findById(Integer zeroaspkId);

	/**
     * Find and return the list of ZeroAsPks by given id's.
     *
     * If orderedReturn true, the return List is ordered and positional relative to the incoming ids.
     *
     * In case of unknown entities:
     *
     * If enabled, A null is inserted into the List at the proper position(s).
     * If disabled, the nulls are not put into the return List.
     *
     * @param zeroaspkIds The id's of the ZeroAsPk to get; value cannot be null.
     * @param orderedReturn Should the return List be ordered and positional in relation to the incoming ids?
     * @return ZeroAsPks associated with the given zeroaspkIds.
     */
    List<ZeroAsPk> findByMultipleIds(List<Integer> zeroaspkIds, boolean orderedReturn);


    /**
     * Updates the details of an existing ZeroAsPk. It replaces all fields of the existing ZeroAsPk with the given zeroAsPk.
     *
     * This method overrides the input field values using Server side or database managed properties defined on ZeroAsPk if any.
     *
     * @param zeroAsPk The details of the ZeroAsPk to be updated; value cannot be null.
     * @return The updated ZeroAsPk.
     * @throws EntityNotFoundException if no ZeroAsPk is found with given input.
     */
    ZeroAsPk update(@Valid ZeroAsPk zeroAsPk);


    /**
     * Partially updates the details of an existing ZeroAsPk. It updates only the
     * fields of the existing ZeroAsPk which are passed in the zeroAsPkPatch.
     *
     * This method overrides the input field values using Server side or database managed properties defined on ZeroAsPk if any.
     *
     * @param zeroaspkId The id of the ZeroAsPk to be deleted; value cannot be null.
     * @param zeroAsPkPatch The partial data of ZeroAsPk which is supposed to be updated; value cannot be null.
     * @return The updated ZeroAsPk.
     * @throws EntityNotFoundException if no ZeroAsPk is found with given input.
     */
    ZeroAsPk partialUpdate(Integer zeroaspkId, Map<String, Object> zeroAsPkPatch);

    /**
     * Deletes an existing ZeroAsPk with the given id.
     *
     * @param zeroaspkId The id of the ZeroAsPk to be deleted; value cannot be null.
     * @return The deleted ZeroAsPk.
     * @throws EntityNotFoundException if no ZeroAsPk found with the given id.
     */
    ZeroAsPk delete(Integer zeroaspkId);

    /**
     * Deletes an existing ZeroAsPk with the given object.
     *
     * @param zeroAsPk The instance of the ZeroAsPk to be deleted; value cannot be null.
     */
    void delete(ZeroAsPk zeroAsPk);

    /**
     * Find all ZeroAsPks matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
     *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
     *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching ZeroAsPks.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
     */
    @Deprecated
    Page<ZeroAsPk> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
     * Find all ZeroAsPks matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching ZeroAsPks.
     *
     * @see Pageable
     * @see Page
     */
    Page<ZeroAsPk> findAll(String query, Pageable pageable);

    /**
     * Exports all ZeroAsPks matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
     */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

    /**
     * Exports all ZeroAsPks matching the given input query to the given exportType format.
     *
     * @param options The export options provided by the user; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @param outputStream The output stream of the file for the exported data to be written to.
     *
     * @see DataExportOptions
     * @see Pageable
     * @see OutputStream
     */
    void export(DataExportOptions options, Pageable pageable, OutputStream outputStream);

    /**
     * Retrieve the count of the ZeroAsPks in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
     * @return The count of the ZeroAsPk.
     */
    long count(String query);

    /**
     * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return Paginated data with included fields.
     *
     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
    Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}