/*Generated by WaveMaker Studio*/
package com.testingallprocedurescenarios.db123__.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.InputStream;
import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.servlet.support.ServletUriComponentsBuilder;
import org.springframework.web.util.UriComponentsBuilder;

import com.fasterxml.jackson.annotation.JsonView;
import com.wavemaker.commons.json.views.JsonViews.BlobAsUrlView;
import com.wavemaker.commons.wrapper.IntegerWrapper;
import com.wavemaker.commons.wrapper.StringWrapper;
import com.wavemaker.runtime.data.export.ExportOptions;
import com.wavemaker.runtime.file.manager.ExportedFileManager;
import com.wavemaker.runtime.file.model.Downloadable;
import com.wavemaker.runtime.util.WMMultipartUtils;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;

import com.testingallprocedurescenarios.db123__.service.Db123__QueryExecutorService;
import com.testingallprocedurescenarios.db123__.models.query.*;

@RestController(value = "Db123__.QueryExecutionController")
@RequestMapping("/db123__/queryExecutor")
@Api(value = "QueryExecutionController", description = "controller class for query execution")
public class QueryExecutionController {

    private static final Logger LOGGER = LoggerFactory.getLogger(QueryExecutionController.class);

    @Autowired
    private Db123__QueryExecutorService queryService;

    @Autowired
	private ExportedFileManager exportedFileManager;

    @RequestMapping(value = "/queries/SV_InsertQuery", method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "Insert Query")
    public IntegerWrapper executeSV_InsertQuery(@Valid @RequestBody SvInsertQueryRequest svInsertQueryRequest, HttpServletRequest _request) {
        LOGGER.debug("Executing named query: SV_InsertQuery");
        Integer _result = queryService.executeSV_InsertQuery(svInsertQueryRequest);
        LOGGER.debug("got the result for named query: SV_InsertQuery, result:{}", _result);
        return new IntegerWrapper(_result);
    }

    @JsonView(BlobAsUrlView.class)
    @RequestMapping(value = "/queries/HQL_GetAllTypes", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "HQL Query Retunring ALl Types")
    public Page<HqlGetAllTypesResponse> executeHQL_GetAllTypes(Pageable pageable, HttpServletRequest _request) {
        LOGGER.debug("Executing named query: HQL_GetAllTypes");
        Page<HqlGetAllTypesResponse> _result = queryService.executeHQL_GetAllTypes(pageable);
        LOGGER.debug("got the result for named query: HQL_GetAllTypes, result:{}", _result);
        UriComponentsBuilder _uriBuilder = ServletUriComponentsBuilder.fromRequest(_request);
        _uriBuilder.path("/content/{_fieldName_}");
        for(HqlGetAllTypesResponse _content : _result.getContent()) {
            Map<String, Object> _properties = new HashMap(1);
            _properties.put("_fieldName_", "blobcol");
            if(_content.getBlobcol() != null) {
                _content.setBlobcol(_uriBuilder.buildAndExpand(_properties).toUriString().getBytes());
            } else {
                _content.setBlobcol(null);
            }
        }
        return _result;
    }

    @ApiOperation(value = "Retrives the BLOB content for property blobcol in query HQL_GetAllTypes")
    @RequestMapping(value = "/queries/HQL_GetAllTypes/content/blobcol", method = RequestMethod.GET, produces = "application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Downloadable getBlobcolContentForHQL_GetAllTypes(@RequestParam(value="downloadAsAttachment", defaultValue = "false") boolean downloadAsAttachment, HttpServletRequest _request) {
        LOGGER.debug("Executing named query: HQL_GetAllTypes");

        InputStream _result = queryService.getBlobcolContentForHQL_GetAllTypes();
        return WMMultipartUtils.buildDownloadResponse(_request, _result, downloadAsAttachment);
    }

    @ApiOperation(value = "Returns downloadable file url for query HQL_GetAllTypes")
    @RequestMapping(value = "/queries/HQL_GetAllTypes/export", method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public StringWrapper exportHQL_GetAllTypes(@RequestBody ExportOptions exportOptions, Pageable pageable) {
        LOGGER.debug("Exporting named query: HQL_GetAllTypes");

        String exportedFileName = exportOptions.getFileName();
        if(exportedFileName == null || exportedFileName.isEmpty()) {
            exportedFileName = "HQL_GetAllTypes";
        }
        exportedFileName += exportOptions.getExportType().getExtension();

        String exportedUrl = exportedFileManager.registerAndGetURL(exportedFileName,
                        outputStream -> queryService.exportHQL_GetAllTypes( exportOptions, pageable, outputStream));

        return new StringWrapper(exportedUrl);
    }

    @JsonView(BlobAsUrlView.class)
    @RequestMapping(value = "/queries/SV_LoggedinId", method = RequestMethod.GET)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @ApiOperation(value = "SV_LoggedinId")
    public Page<SvLoggedinIdResponse> executeSV_LoggedinId(Pageable pageable, HttpServletRequest _request) {
        LOGGER.debug("Executing named query: SV_LoggedinId");
        Page<SvLoggedinIdResponse> _result = queryService.executeSV_LoggedinId(pageable);
        LOGGER.debug("got the result for named query: SV_LoggedinId, result:{}", _result);
        UriComponentsBuilder _uriBuilder = ServletUriComponentsBuilder.fromRequest(_request);
        _uriBuilder.path("/content/{_fieldName_}");
        for(SvLoggedinIdResponse _content : _result.getContent()) {
            Map<String, Object> _properties = new HashMap(1);
            _properties.put("_fieldName_", "blobCol");
            if(_content.getBlobCol() != null) {
                _content.setBlobCol(_uriBuilder.buildAndExpand(_properties).toUriString().getBytes());
            } else {
                _content.setBlobCol(null);
            }
        }
        return _result;
    }

    @ApiOperation(value = "Retrives the BLOB content for property blobCol in query SV_LoggedinId")
    @RequestMapping(value = "/queries/SV_LoggedinId/content/blobCol", method = RequestMethod.GET, produces = "application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Downloadable getBlobColContentForSV_LoggedinId(@RequestParam(value="downloadAsAttachment", defaultValue = "false") boolean downloadAsAttachment, HttpServletRequest _request) {
        LOGGER.debug("Executing named query: SV_LoggedinId");

        InputStream _result = queryService.getBlobColContentForSV_LoggedinId();
        return WMMultipartUtils.buildDownloadResponse(_request, _result, downloadAsAttachment);
    }

    @ApiOperation(value = "Returns downloadable file url for query SV_LoggedinId")
    @RequestMapping(value = "/queries/SV_LoggedinId/export", method = RequestMethod.POST)
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public StringWrapper exportSV_LoggedinId(@RequestBody ExportOptions exportOptions, Pageable pageable) {
        LOGGER.debug("Exporting named query: SV_LoggedinId");

        String exportedFileName = exportOptions.getFileName();
        if(exportedFileName == null || exportedFileName.isEmpty()) {
            exportedFileName = "SV_LoggedinId";
        }
        exportedFileName += exportOptions.getExportType().getExtension();

        String exportedUrl = exportedFileManager.registerAndGetURL(exportedFileName,
                        outputStream -> queryService.exportSV_LoggedinId( exportOptions, pageable, outputStream));

        return new StringWrapper(exportedUrl);
    }

}