/*Generated by WaveMaker Studio*/
package com.testingallprocedurescenarios.dbscenarios.models.procedure;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.List;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class SvCurrentDateResponse implements Serializable {


    @ColumnAlias("content")
    private List<SvCurrentDateResponseContent> content;

    public List<SvCurrentDateResponseContent> getContent() {
        return this.content;
    }

    public void setContent(List<SvCurrentDateResponseContent> content) {
        this.content = content;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SvCurrentDateResponse)) return false;
        final SvCurrentDateResponse svCurrentDateResponse = (SvCurrentDateResponse) o;
        return Objects.equals(getContent(), svCurrentDateResponse.getContent());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getContent());
    }
}