/*Generated by WaveMaker Studio*/
package com.testingallprocedurescenarios.db123__.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.LocalDateTime;
import java.util.Date;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonProperty.Access;
import com.fasterxml.jackson.annotation.JsonView;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.wavemaker.commons.json.serializer.ByteArrayToStringSerializer;
import com.wavemaker.commons.json.views.JsonViews.BlobAsUrlView;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class HqlGetAllTypesResponse implements Serializable {


    @ColumnAlias("ASSIGNEDID")
    private Integer assignedid;

    @ColumnAlias("BYTECOL")
    private Byte bytecol;

    @ColumnAlias("SHORTCOL")
    private Short shortcol;

    @ColumnAlias("LONGCOL")
    private BigInteger longcol;

    @ColumnAlias("DOUBLECOL")
    private Double doublecol;

    @ColumnAlias("BIGINTCOL")
    private BigInteger bigintcol;

    @ColumnAlias("FLOATCOL")
    private Float floatcol;

    @ColumnAlias("BIGDECCOL")
    private BigDecimal bigdeccol;

    @ColumnAlias("CHARCOL")
    private String charcol;

    @ColumnAlias("STRINGCOL")
    private String stringcol;

    @ColumnAlias("TEXTCOL")
    private String textcol;

    @ColumnAlias("CLOBCOL")
    private String clobcol;

    @ColumnAlias("DATECOL")
    private Date datecol;

    @ColumnAlias("TIMECOL")
    private Date timecol;

    @ColumnAlias("DATETIMECOL")
    private LocalDateTime datetimecol;

    @ColumnAlias("TIMESTAMPCOL")
    private LocalDateTime timestampcol;

    @ColumnAlias("BOOLEANCOL")
    private Boolean booleancol;

        @JsonView(BlobAsUrlView.class)
    @JsonSerialize(using = ByteArrayToStringSerializer.class)
    @JsonProperty(access = Access.READ_ONLY)
    @ColumnAlias("BLOBCOL")
    private byte[] blobcol;

    public Integer getAssignedid() {
        return this.assignedid;
    }

    public void setAssignedid(Integer assignedid) {
        this.assignedid = assignedid;
    }

    public Byte getBytecol() {
        return this.bytecol;
    }

    public void setBytecol(Byte bytecol) {
        this.bytecol = bytecol;
    }

    public Short getShortcol() {
        return this.shortcol;
    }

    public void setShortcol(Short shortcol) {
        this.shortcol = shortcol;
    }

    public BigInteger getLongcol() {
        return this.longcol;
    }

    public void setLongcol(BigInteger longcol) {
        this.longcol = longcol;
    }

    public Double getDoublecol() {
        return this.doublecol;
    }

    public void setDoublecol(Double doublecol) {
        this.doublecol = doublecol;
    }

    public BigInteger getBigintcol() {
        return this.bigintcol;
    }

    public void setBigintcol(BigInteger bigintcol) {
        this.bigintcol = bigintcol;
    }

    public Float getFloatcol() {
        return this.floatcol;
    }

    public void setFloatcol(Float floatcol) {
        this.floatcol = floatcol;
    }

    public BigDecimal getBigdeccol() {
        return this.bigdeccol;
    }

    public void setBigdeccol(BigDecimal bigdeccol) {
        this.bigdeccol = bigdeccol;
    }

    public String getCharcol() {
        return this.charcol;
    }

    public void setCharcol(String charcol) {
        this.charcol = charcol;
    }

    public String getStringcol() {
        return this.stringcol;
    }

    public void setStringcol(String stringcol) {
        this.stringcol = stringcol;
    }

    public String getTextcol() {
        return this.textcol;
    }

    public void setTextcol(String textcol) {
        this.textcol = textcol;
    }

    public String getClobcol() {
        return this.clobcol;
    }

    public void setClobcol(String clobcol) {
        this.clobcol = clobcol;
    }

    public Date getDatecol() {
        return this.datecol;
    }

    public void setDatecol(Date datecol) {
        this.datecol = datecol;
    }

    public Date getTimecol() {
        return this.timecol;
    }

    public void setTimecol(Date timecol) {
        this.timecol = timecol;
    }

    public LocalDateTime getDatetimecol() {
        return this.datetimecol;
    }

    public void setDatetimecol(LocalDateTime datetimecol) {
        this.datetimecol = datetimecol;
    }

    public LocalDateTime getTimestampcol() {
        return this.timestampcol;
    }

    public void setTimestampcol(LocalDateTime timestampcol) {
        this.timestampcol = timestampcol;
    }

    public Boolean getBooleancol() {
        return this.booleancol;
    }

    public void setBooleancol(Boolean booleancol) {
        this.booleancol = booleancol;
    }

    public byte[] getBlobcol() {
        return this.blobcol;
    }

    public void setBlobcol(byte[] blobcol) {
        this.blobcol = blobcol;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof HqlGetAllTypesResponse)) return false;
        final HqlGetAllTypesResponse hqlGetAllTypesResponse = (HqlGetAllTypesResponse) o;
        return Objects.equals(getAssignedid(), hqlGetAllTypesResponse.getAssignedid()) &&
                Objects.equals(getBytecol(), hqlGetAllTypesResponse.getBytecol()) &&
                Objects.equals(getShortcol(), hqlGetAllTypesResponse.getShortcol()) &&
                Objects.equals(getLongcol(), hqlGetAllTypesResponse.getLongcol()) &&
                Objects.equals(getDoublecol(), hqlGetAllTypesResponse.getDoublecol()) &&
                Objects.equals(getBigintcol(), hqlGetAllTypesResponse.getBigintcol()) &&
                Objects.equals(getFloatcol(), hqlGetAllTypesResponse.getFloatcol()) &&
                Objects.equals(getBigdeccol(), hqlGetAllTypesResponse.getBigdeccol()) &&
                Objects.equals(getCharcol(), hqlGetAllTypesResponse.getCharcol()) &&
                Objects.equals(getStringcol(), hqlGetAllTypesResponse.getStringcol()) &&
                Objects.equals(getTextcol(), hqlGetAllTypesResponse.getTextcol()) &&
                Objects.equals(getClobcol(), hqlGetAllTypesResponse.getClobcol()) &&
                Objects.equals(getDatecol(), hqlGetAllTypesResponse.getDatecol()) &&
                Objects.equals(getTimecol(), hqlGetAllTypesResponse.getTimecol()) &&
                Objects.equals(getDatetimecol(), hqlGetAllTypesResponse.getDatetimecol()) &&
                Objects.equals(getTimestampcol(), hqlGetAllTypesResponse.getTimestampcol()) &&
                Objects.equals(getBooleancol(), hqlGetAllTypesResponse.getBooleancol()) &&
                Objects.equals(getBlobcol(), hqlGetAllTypesResponse.getBlobcol());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getAssignedid(),
                getBytecol(),
                getShortcol(),
                getLongcol(),
                getDoublecol(),
                getBigintcol(),
                getFloatcol(),
                getBigdeccol(),
                getCharcol(),
                getStringcol(),
                getTextcol(),
                getClobcol(),
                getDatecol(),
                getTimecol(),
                getDatetimecol(),
                getTimestampcol(),
                getBooleancol(),
                getBlobcol());
    }
}