/*Generated by WaveMaker Studio*/
package com.testingallprocedurescenarios.db123__.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.Objects;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

public class SvInsertQueryRequest implements Serializable {


    @JsonProperty("ASSIGNEDID")
    @NotNull
    private Integer assignedid;

    @JsonProperty("BYTECOL")
    @NotNull
    private Byte bytecol;

    @JsonProperty("SHORTCOL")
    @NotNull
    private Short shortcol;

    @JsonProperty("INTCOL")
    @NotNull
    private Integer intcol;

    @JsonProperty("FLOATCOL")
    @NotNull
    private Float floatcol;

    @JsonProperty("LONGCOL")
    @NotNull
    private Long longcol;

    @JsonProperty("DOUBLECOL")
    @NotNull
    private Double doublecol;

    @JsonProperty("BIGINTCOL")
    @NotNull
    private BigInteger bigintcol;

    @JsonProperty("BIGDECCOL")
    @NotNull
    private BigDecimal bigdeccol;

    @JsonProperty("CHARCOL")
    @NotNull
    private Character charcol;

    @JsonProperty("STRINGCOL")
    @NotNull
    private String stringcol;

    @JsonProperty("TEXTCOL")
    @NotNull
    private String textcol;

    @JsonProperty("CLOBCOL")
    @NotNull
    private String clobcol;

    @JsonProperty("DATECOL")
    @NotNull
    private Date datecol;

    @JsonProperty("TIMECOL")
    @NotNull
    private Time timecol;

    @JsonProperty("BOOLEANCOL")
    @NotNull
    private Boolean booleancol;

    @JsonProperty("DATETIMECOL")
    @NotNull
    private LocalDateTime datetimecol;

    @JsonProperty("TIMESTAMPCOL")
    @NotNull
    private Timestamp timestampcol;

    public Integer getAssignedid() {
        return this.assignedid;
    }

    public void setAssignedid(Integer assignedid) {
        this.assignedid = assignedid;
    }

    public Byte getBytecol() {
        return this.bytecol;
    }

    public void setBytecol(Byte bytecol) {
        this.bytecol = bytecol;
    }

    public Short getShortcol() {
        return this.shortcol;
    }

    public void setShortcol(Short shortcol) {
        this.shortcol = shortcol;
    }

    public Integer getIntcol() {
        return this.intcol;
    }

    public void setIntcol(Integer intcol) {
        this.intcol = intcol;
    }

    public Float getFloatcol() {
        return this.floatcol;
    }

    public void setFloatcol(Float floatcol) {
        this.floatcol = floatcol;
    }

    public Long getLongcol() {
        return this.longcol;
    }

    public void setLongcol(Long longcol) {
        this.longcol = longcol;
    }

    public Double getDoublecol() {
        return this.doublecol;
    }

    public void setDoublecol(Double doublecol) {
        this.doublecol = doublecol;
    }

    public BigInteger getBigintcol() {
        return this.bigintcol;
    }

    public void setBigintcol(BigInteger bigintcol) {
        this.bigintcol = bigintcol;
    }

    public BigDecimal getBigdeccol() {
        return this.bigdeccol;
    }

    public void setBigdeccol(BigDecimal bigdeccol) {
        this.bigdeccol = bigdeccol;
    }

    public Character getCharcol() {
        return this.charcol;
    }

    public void setCharcol(Character charcol) {
        this.charcol = charcol;
    }

    public String getStringcol() {
        return this.stringcol;
    }

    public void setStringcol(String stringcol) {
        this.stringcol = stringcol;
    }

    public String getTextcol() {
        return this.textcol;
    }

    public void setTextcol(String textcol) {
        this.textcol = textcol;
    }

    public String getClobcol() {
        return this.clobcol;
    }

    public void setClobcol(String clobcol) {
        this.clobcol = clobcol;
    }

    public Date getDatecol() {
        return this.datecol;
    }

    public void setDatecol(Date datecol) {
        this.datecol = datecol;
    }

    public Time getTimecol() {
        return this.timecol;
    }

    public void setTimecol(Time timecol) {
        this.timecol = timecol;
    }

    public Boolean getBooleancol() {
        return this.booleancol;
    }

    public void setBooleancol(Boolean booleancol) {
        this.booleancol = booleancol;
    }

    public LocalDateTime getDatetimecol() {
        return this.datetimecol;
    }

    public void setDatetimecol(LocalDateTime datetimecol) {
        this.datetimecol = datetimecol;
    }

    public Timestamp getTimestampcol() {
        return this.timestampcol;
    }

    public void setTimestampcol(Timestamp timestampcol) {
        this.timestampcol = timestampcol;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof SvInsertQueryRequest)) return false;
        final SvInsertQueryRequest svInsertQueryRequest = (SvInsertQueryRequest) o;
        return Objects.equals(getAssignedid(), svInsertQueryRequest.getAssignedid()) &&
                Objects.equals(getBytecol(), svInsertQueryRequest.getBytecol()) &&
                Objects.equals(getShortcol(), svInsertQueryRequest.getShortcol()) &&
                Objects.equals(getIntcol(), svInsertQueryRequest.getIntcol()) &&
                Objects.equals(getFloatcol(), svInsertQueryRequest.getFloatcol()) &&
                Objects.equals(getLongcol(), svInsertQueryRequest.getLongcol()) &&
                Objects.equals(getDoublecol(), svInsertQueryRequest.getDoublecol()) &&
                Objects.equals(getBigintcol(), svInsertQueryRequest.getBigintcol()) &&
                Objects.equals(getBigdeccol(), svInsertQueryRequest.getBigdeccol()) &&
                Objects.equals(getCharcol(), svInsertQueryRequest.getCharcol()) &&
                Objects.equals(getStringcol(), svInsertQueryRequest.getStringcol()) &&
                Objects.equals(getTextcol(), svInsertQueryRequest.getTextcol()) &&
                Objects.equals(getClobcol(), svInsertQueryRequest.getClobcol()) &&
                Objects.equals(getDatecol(), svInsertQueryRequest.getDatecol()) &&
                Objects.equals(getTimecol(), svInsertQueryRequest.getTimecol()) &&
                Objects.equals(getBooleancol(), svInsertQueryRequest.getBooleancol()) &&
                Objects.equals(getDatetimecol(), svInsertQueryRequest.getDatetimecol()) &&
                Objects.equals(getTimestampcol(), svInsertQueryRequest.getTimestampcol());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getAssignedid(),
                getBytecol(),
                getShortcol(),
                getIntcol(),
                getFloatcol(),
                getLongcol(),
                getDoublecol(),
                getBigintcol(),
                getBigdeccol(),
                getCharcol(),
                getStringcol(),
                getTextcol(),
                getClobcol(),
                getDatecol(),
                getTimecol(),
                getBooleancol(),
                getDatetimecol(),
                getTimestampcol());
    }
}